# cs/cs_ch18.py

cs_ch18_mcq_answers = {
    "Which of the following is used to define a list?": "A",
    "What is the index of the first element in a list?": "C",
    "What does list.append(5) do?": "A",
    "Which method removes an element by value?": "C",
    "Which method removes element by index?": "D",
    "What is the output of len([1,2,3])?": "A",
    "Which of the following can lists store?": "D",
    "Which operator is used to join two lists?": "B",
    "What does list1.extend(list2) do?": "C",
    "Which method sorts a list in place?": "B",
    "What does list.pop() do?": "C",
    "Which method reverses a list?": "D",
    "What is the output of [1,2,3][0]?": "A",
    "What is the result of list slicing?": "B",
    "What does list.insert(2, 100) do?": "C",
    "Which is not a valid list method?": "D",
    "Which method counts occurrences of an element?": "B",
    "Which method copies a list?": "A",
    "Lists in Python are:": "B",
    "Which of these is mutable?": "A",
    "What will list.index(5) return?": "D",
    "What does list.clear() do?": "A",
    "What does list.sort(reverse=True) do?": "B",
    "How do you declare an empty list?": "C",
    "Which function returns maximum from list?": "A",
    "Which function returns minimum from list?": "B"
}

cs_ch18_mcq_options = {
    "Which of the following is used to define a list?": "A. [ ]  B. { }  C. ( )  D. < >",
    "What is the index of the first element in a list?": "A. 1  B. -1  C. 0  D. 2",
    "What does list.append(5) do?": "A. Adds 5 at the end  B. Adds 5 at the start  C. Replaces all  D. Deletes 5",
    "Which method removes an element by value?": "A. pop()  B. del  C. remove()  D. erase()",
    "Which method removes element by index?": "A. clear()  B. delete()  C. remove()  D. pop()",
    "What is the output of len([1,2,3])?": "A. 3  B. 2  C. 1  D. 0",
    "Which of the following can lists store?": "A. int  B. str  C. float  D. All",
    "Which operator is used to join two lists?": "A. *  B. +  C. &  D. %%",
    "What does list1.extend(list2) do?": "A. Replaces list1  B. Reverses list2  C. Adds list2 to list1  D. Nothing",
    "Which method sorts a list in place?": "A. order()  B. sort()  C. sorted()  D. arrange()",
    "What does list.pop() do?": "A. Adds item  B. Reverses list  C. Removes last element  D. Returns list length",
    "Which method reverses a list?": "A. return()  B. invert()  C. flip()  D. reverse()",
    "What is the output of [1,2,3][0]?": "A. 1  B. 2  C. 3  D. 0",
    "What is the result of list slicing?": "A. Tuple  B. List  C. Dict  D. Set",
    "What does list.insert(2, 100) do?": "A. Deletes 100  B. Adds at end  C. Inserts 100 at index 2  D. Error",
    "Which is not a valid list method?": "A. remove()  B. pop()  C. insert()  D. split()",
    "Which method counts occurrences of an element?": "A. len()  B. count()  C. sum()  D. times()",
    "Which method copies a list?": "A. copy()  B. clone()  C. list()  D. duplicate()",
    "Lists in Python are:": "A. Immutable  B. Mutable  C. Static  D. Constant",
    "Which of these is mutable?": "A. List  B. String  C. Tuple  D. Integer",
    "What will list.index(5) return?": "A. Value  B. True  C. Error  D. Index of 5",
    "What does list.clear() do?": "A. Removes all elements  B. Sets all to None  C. Reverses list  D. Nothing",
    "What does list.sort(reverse=True) do?": "A. Sorts ascending  B. Sorts descending  C. Returns sorted list  D. Clears list",
    "How do you declare an empty list?": "A. {}  B. ()  C. []  D. <>",
    "Which function returns maximum from list?": "A. max()  B. highest()  C. top()  D. large()",
    "Which function returns minimum from list?": "A. small()  B. min()  C. low()  D. bottom()"
}

true_false_cs_ch18 = {
    "Lists in Python are mutable.": "T",
    "List indexing starts at 1.": "F",
    "append() adds an item to the end of the list.": "T",
    "remove() deletes element by index.": "F",
    "pop() removes the last element by default.": "T",
    "List slicing creates a new list.": "T",
    "sort() modifies the list in place.": "T",
    "reverse() reverses the list in place.": "T",
    "copy() returns a new reference to same list.": "F",
    "insert() adds a value at a specific index.": "T",
    "You can mix data types in lists.": "T",
    "Lists cannot be nested.": "F",
    "len() returns number of elements in a list.": "T",
    "Lists are immutable like strings.": "F",
    "List methods include append, remove, insert.": "T",
    "You can join two lists using +.": "T",
    "clear() empties the entire list.": "T",
    "Tuples are mutable like lists.": "F",
    "extend() adds all items from one list to another.": "T",
    "split() is a method for lists.": "F",
    "pop(index) removes item at given index.": "T",
    "min(list) returns smallest element.": "T",
    "max() gives highest value in a list.": "T",
    "List indexing can use negative numbers.": "T",
    "Lists can hold strings and numbers together.": "T",
    "count() returns how many times a value occurs.": "T"
}
