# cs/cs_ch8.py

cs_ch8_mcq_answers = {
    "Which of the following is a correct way to define a list in Python?": "A",
    "What is the index of the first element in a list?": "B",
    "Which method is used to add an element at the end of the list?": "C",
    "Which method removes a specific item from the list?": "A",
    "What is the output of len([10, 20, 30])?": "D",
    "Which of the following adds an element at a specific position in a list?": "B",
    "What will be the result of [1,2,3] + [4,5]?": "C",
    "How to remove all items from a list?": "D",
    "What does the list method pop() do?": "A",
    "What is the output of [1, 2, 3][1]?": "B",
    "Which operator is used to check membership in a list?": "C",
    "Which of these will create an empty list?": "A",
    "What is the result of [2]*3?": "B",
    "How do you sort a list permanently?": "C",
    "Which method returns the index of the first matching element?": "D",
    "Which method is used to reverse the elements of a list?": "A",
    "What does append() return?": "B",
    "Negative indices in lists refer to:": "C",
    "Which method inserts a value at a specified position?": "D",
    "What will be the result of list('abc')?": "A"
}

cs_ch8_mcq_options = {
    "Which of the following is a correct way to define a list in Python?": "A. mylist = [1, 2, 3]  B. mylist = {1, 2, 3}  C. mylist = (1, 2, 3)  D. mylist = <1,2,3>",
    "What is the index of the first element in a list?": "A. 1  B. 0  C. -1  D. None",
    "Which method is used to add an element at the end of the list?": "A. insert()  B. extend()  C. append()  D. add()",
    "Which method removes a specific item from the list?": "A. remove()  B. discard()  C. pop()  D. delete()",
    "What is the output of len([10, 20, 30])?": "A. 2  B. 1  C. 0  D. 3",
    "Which of the following adds an element at a specific position in a list?": "A. append()  B. insert()  C. add()  D. push()",
    "What will be the result of [1,2,3] + [4,5]?": "A. [5,7,8]  B. [4,5,1,2,3]  C. [1,2,3,4,5]  D. Error",
    "How to remove all items from a list?": "A. del list  B. list.remove_all()  C. list.delete()  D. list.clear()",
    "What does the list method pop() do?": "A. Removes and returns last item  B. Adds item  C. Removes all items  D. Returns list length",
    "What is the output of [1, 2, 3][1]?": "A. 1  B. 2  C. 3  D. Error",
    "Which operator is used to check membership in a list?": "A. ==  B. inrange  C. in  D. has",
    "Which of these will create an empty list?": "A. []  B. {}  C. ()  D. set()",
    "What is the result of [2]*3?": "A. [2, 3]  B. [2, 2, 2]  C. [3, 2]  D. [6]",
    "How do you sort a list permanently?": "A. list.sorted()  B. sort(list)  C. list.sort()  D. sorted(list)",
    "Which method returns the index of the first matching element?": "A. find()  B. locate()  C. match()  D. index()",
    "Which method is used to reverse the elements of a list?": "A. reverse()  B. invert()  C. backward()  D. flip()",
    "What does append() return?": "A. the new list  B. nothing (None)  C. the index  D. the item added",
    "Negative indices in lists refer to:": "A. invalid entries  B. error  C. positions from the end  D. keys",
    "Which method inserts a value at a specified position?": "A. push()  B. place()  C. add()  D. insert()",
    "What will be the result of list('abc')?": "A. ['a','b','c']  B. ['abc']  C. 'a','b','c'  D. Error"
}

true_false_cs_ch8 = {
    "Lists in Python are mutable.": "T",
    "A list can store multiple data types.": "T",
    "Indexing in lists starts from 1.": "F",
    "The append() method adds an element at the end of the list.": "T",
    "The pop() method always removes the first element.": "F",
    "The clear() method removes all elements of a list.": "T",
    "The insert() method can place an element at any index.": "T",
    "Negative indexing in Python starts from -1.": "T",
    "The len() function returns the number of elements in a list.": "T",
    "Lists are immutable in Python.": "F",
    "The sort() method returns a new sorted list.": "F",
    "We can use + operator to concatenate lists.": "T",
    "A list cannot contain duplicate values.": "F",
    "The remove() method deletes all matching elements.": "F",
    "You can use slicing on lists.": "T",
    "The extend() method adds multiple elements to a list.": "T",
    "An empty list is represented as [].": "T",
    "Lists can only contain integers.": "F",
    "The del keyword can delete a list completely.": "T",
    "The max() function returns the largest element in a list.": "T",
    "We cannot use for loops with lists.": "F",
    "The index() method throws an error if value not found.": "T",
    "Lists are ordered collections in Python.": "T",
    "You can use the 'in' operator to check if an item exists in a list.": "T",
    "A list can be nested within another list.": "T"
}
