# cs/cs_ch4.py

cs_ch4_mcq_answers = {
    "Which of the following is a step in the problem-solving process?": "A",
    "The first step in problem solving is:": "B",
    "Which diagram uses shapes like ovals, rectangles, and diamonds to represent logic?": "C",
    "What is pseudocode?": "D",
    "Which of these is not a valid flowchart symbol?": "A",
    "A decision in a flowchart is represented by:": "C",
    "What is an algorithm?": "A",
    "Pseudocode helps in:": "B",
    "Which programming language is used in this chapter for problem solving?": "C",
    "Which of the following is an advantage of flowcharts?": "D",
    "What shape is used to represent input/output in a flowchart?": "B",
    "What does the rectangle in a flowchart represent?": "C",
    "What is the purpose of a flowchart?": "A",
    "Which of the following is best for writing algorithms?": "D",
    "What does a diamond in a flowchart indicate?": "C",
    "Python is an example of:": "A",
    "The keyword used for decision-making in Python is:": "B",
    "The process of breaking down a big problem into smaller parts is called:": "C",
    "What is the correct syntax to start a loop in Python?": "D",
    "Which keyword is used to define a function in Python?": "A"
}

cs_ch4_mcq_options = {
    "Which of the following is a step in the problem-solving process?": "A. Understanding the problem  B. Writing code only  C. Debugging only  D. None",
    "The first step in problem solving is:": "A. Coding  B. Understanding the problem  C. Writing pseudocode  D. Making a flowchart",
    "Which diagram uses shapes like ovals, rectangles, and diamonds to represent logic?": "A. Algorithm  B. Pseudocode  C. Flowchart  D. Blueprint",
    "What is pseudocode?": "A. Code in Python  B. Compiled code  C. Visual diagram  D. Informal description of logic",
    "Which of these is not a valid flowchart symbol?": "A. Circle  B. Oval  C. Diamond  D. Rectangle",
    "A decision in a flowchart is represented by:": "A. Rectangle  B. Oval  C. Diamond  D. Arrow",
    "What is an algorithm?": "A. Step-by-step solution  B. Flowchart  C. Programming code  D. Python syntax",
    "Pseudocode helps in:": "A. Writing Python  B. Planning logic  C. Debugging  D. Graphics",
    "Which programming language is used in this chapter for problem solving?": "A. Java  B. C++  C. Python  D. JavaScript",
    "Which of the following is an advantage of flowcharts?": "A. Difficult to draw  B. Requires coding  C. Time-consuming  D. Easy to understand",
    "What shape is used to represent input/output in a flowchart?": "A. Rectangle  B. Parallelogram  C. Oval  D. Diamond",
    "What does the rectangle in a flowchart represent?": "A. Input/output  B. Decision  C. Process  D. Connector",
    "What is the purpose of a flowchart?": "A. Visualize logic  B. Run code  C. Debug error  D. Save memory",
    "Which of the following is best for writing algorithms?": "A. Python code  B. Flowchart  C. Circle diagram  D. Pseudocode",
    "What does a diamond in a flowchart indicate?": "A. Start/End  B. Input/Output  C. Decision  D. Processing",
    "Python is an example of:": "A. High-level language  B. Machine language  C. Assembly language  D. Scripting only",
    "The keyword used for decision-making in Python is:": "A. def  B. if  C. for  D. input",
    "The process of breaking down a big problem into smaller parts is called:": "A. Compiling  B. Logic design  C. Modular programming  D. Debugging",
    "What is the correct syntax to start a loop in Python?": "A. loop()  B. if loop:  C. repeat:  D. for i in range()",
    "Which keyword is used to define a function in Python?": "A. def  B. function  C. create  D. define"
}

true_false_cs_ch4 = {
    "An algorithm is a step-by-step solution to a problem.": "T",
    "Flowcharts are only used in mathematics.": "F",
    "A parallelogram in a flowchart represents a process.": "F",
    "Pseudocode is written in any programming language.": "F",
    "Python can be used for writing problem-solving solutions.": "T",
    "A rectangle in a flowchart represents decision-making.": "F",
    "The diamond shape is used for decision in a flowchart.": "T",
    "Understanding the problem is the last step in problem solving.": "F",
    "Flowcharts can help visualize the flow of logic.": "T",
    "Pseudocode helps convert ideas into actual programs easily.": "T",
    "The keyword 'if' is used in Python for loops.": "F",
    "Modular programming means solving problems as one big unit.": "F",
    "The flowchart begins and ends with an oval symbol.": "T",
    "Algorithms are only used by computer scientists.": "F",
    "Python uses 'def' to define functions.": "T",
    "Pseudocode must follow Python syntax exactly.": "F",
    "A flowchart cannot have more than one start point.": "F",
    "Problem solving in computing involves writing pseudocode and drawing flowcharts.": "T",
    "The ‘for’ keyword is used to define conditions in Python.": "F",
    "Flowcharts are useful for debugging code.": "T",
    "Pseudocode is the same as writing in Python.": "F",
    "One advantage of flowcharts is easy modification.": "T",
    "In a flowchart, a circle is used for starting the program.": "F",
    "Python is a high-level programming language.": "T",
    "The process symbol in a flowchart is a rectangle.": "T"
}