cs_ch14_mcq_options = {
    "What is a module in Python?": "A) A single function    B) A program file containing Python code    C) A keyword    D) A Python operator",
    "Which keyword is used to include a module in Python?": "A) include    B) import    C) using    D) use",
    "Which of the following is a built-in module?": "A) math    B) mymodule    C) usermod    D) pyfile",
    "What is the extension of a Python module file?": "A) .mod    B) .pym    C) .py    D) .txt",
    "Which function lists all functions/objects in a module?": "A) list()    B) dir()    C) show()    D) view()",
    "How do you access the sqrt() function from math module?": "A) math.sqrt()    B) sqrt(math)    C) sqrt    D) math::sqrt()",
    "What does 'from math import *' do?": "A) Imports all math functions    B) Imports only sqrt    C) Error    D) Imports math module with alias",
    "Which of the following is a user-defined module?": "A) math    B) random    C) myutils.py    D) sys",
    "How do you alias a module while importing?": "A) import module as alias    B) include module = alias    C) alias import module    D) use alias(module)",
    "What is the purpose of using modules?": "A) To divide program    B) To reuse code    C) To organize code    D) All of these",
    "Which statement is correct?": "A) Modules cannot contain functions    B) Modules can have functions, variables, classes    C) Modules only have comments    D) Modules must start with main()",
    "What will import math and print(math.pi) output?": "A) 3.14    B) 3.141592653589793    C) Error    D) pi",
    "Which method is used to remove a module from memory?": "A) del    B) unload()    C) remove    D) None",
    "Where does Python look for modules by default?": "A) sys.path    B) PATH variable    C) current directory only    D) /usr/bin",
    "How can we see the location of an imported module?": "A) module.location    B) module.__file__    C) getfile(module)    D) module.path()",
    "Which module gives system-specific parameters?": "A) os    B) random    C) sys    D) math",
    "What will 'import myfile' do?": "A) Import myfile.py    B) Error    C) Import string    D) Import package",
    "Which is true for 'import random'?": "A) You can use random.randint()    B) randint() is directly usable    C) It will give error    D) It changes sys.path",
    "Which function of random module returns random integer?": "A) random()    B) randint()    C) randrange()    D) choice()",
    "How do you find documentation of a module?": "A) help(module)    B) doc(module)    C) info(module)    D) module.doc()",
    "What does __name__ == '__main__' indicate?": "A) Imported module    B) Directly run script    C) Built-in module    D) Random import",
    "Which module is used to work with directories?": "A) os    B) sys    C) time    D) random",
    "Which file can be imported as a module?": "A) Any .py file    B) Only built-in files    C) Only system files    D) Only special files",
    "What does 'import os' allow you to do?": "A) Work with operating system functions    B) Run Python interpreter    C) Make web requests    D) Perform math calculations",
    "Which module provides time-related functions?": "A) random    B) time    C) os    D) sys",
    "What does random.choice([1, 2, 3]) return?": "A) 1    B) 2    C) 3    D) Any of the three",
    "Which symbol is used to separate module and function?": "A) . (dot)    B) ::    C) ->    D) ,",
    "What is a package in Python?": "A) Collection of modules    B) Single function    C) Built-in keyword    D) Module extension",
    "Which of these is a valid way to import only one function?": "A) from math import sqrt    B) import math.sqrt    C) get math.sqrt    D) math::sqrt",
    "Which Python file will not be treated as a module?": "A) One without .py extension    B) One without functions    C) One with only variables    D) All files are modules"
}

cs_ch14_mcq_answers = {
    "What is a module in Python?": "B",
    "Which keyword is used to include a module in Python?": "B",
    "Which of the following is a built-in module?": "A",
    "What is the extension of a Python module file?": "C",
    "Which function lists all functions/objects in a module?": "B",
    "How do you access the sqrt() function from math module?": "A",
    "What does 'from math import *' do?": "A",
    "Which of the following is a user-defined module?": "C",
    "How do you alias a module while importing?": "A",
    "What is the purpose of using modules?": "D",
    "Which statement is correct?": "B",
    "What will import math and print(math.pi) output?": "B",
    "Which method is used to remove a module from memory?": "A",
    "Where does Python look for modules by default?": "A",
    "How can we see the location of an imported module?": "B",
    "Which module gives system-specific parameters?": "C",
    "What will 'import myfile' do?": "A",
    "Which is true for 'import random'?": "A",
    "Which function of random module returns random integer?": "B",
    "How do you find documentation of a module?": "A",
    "What does __name__ == '__main__' indicate?": "B",
    "Which module is used to work with directories?": "A",
    "Which file can be imported as a module?": "A",
    "What does 'import os' allow you to do?": "A",
    "Which module provides time-related functions?": "B",
    "What does random.choice([1, 2, 3]) return?": "D",
    "Which symbol is used to separate module and function?": "A",
    "What is a package in Python?": "A",
    "Which of these is a valid way to import only one function?": "A",
    "Which Python file will not be treated as a module?": "A"
}

true_false_cs_ch14 = {
    "Modules allow code reuse.": "True",
    "The import keyword is used to include modules.": "True",
    "Python modules must have a .py extension.": "True",
    "math is a built-in Python module.": "True",
    "User-defined modules are not allowed in Python.": "False",
    "The random module is used for generating random values.": "True",
    "We can alias a module during import using 'as'.": "True",
    "dir() shows the contents of a module.": "True",
    "We cannot import specific functions from a module.": "False",
    "from math import * imports only sqrt function.": "False",
    "Modules can contain variables and functions.": "True",
    "We cannot import a module twice.": "False",
    "sys.path stores module search locations.": "True",
    "os module provides operating system interaction.": "True",
    "math module contains string functions.": "False",
    "Modules help keep code organized.": "True",
    "import math makes all math functions available.": "True",
    "from module import function allows direct use of function.": "True",
    "__name__ == '__main__' is True only when run directly.": "True",
    "Packages are a collection of modules.": "True",
    "Any Python file can be imported as a module.": "True",
    "The help() function shows module documentation.": "True",
    "os.getcwd() gives current directory.": "True",
    "importing a non-existent module gives warning only.": "False",
    "Modules cannot have classes.": "False",
    "You must use .py extension to import file as module.": "True",
    "You can use random.choice to choose random items from a list.": "True",
    "Python automatically loads all modules on startup.": "False",
    "dir(math) will list all available math functions.": "True",
    "A module can be shared across multiple Python files.": "True"
}