# cs/cs_ch6.py

cs_ch6_mcq_answers = {
    "Which statement is used for decision making in Python?": "A",
    "Which of the following is not a valid conditional statement in Python?": "C",
    "What is the keyword used for 'else if' in Python?": "B",
    "What will 'if 0:' evaluate to?": "C",
    "Which loop in Python is used when the number of iterations is known?": "D",
    "What is the output of: print(5 > 3 and 4 < 2)?": "B",
    "Which of the following is a valid loop in Python?": "A",
    "Which of the following will execute a loop 5 times?": "C",
    "Which statement is used to skip the rest of the loop and continue with next iteration?": "D",
    "Which statement is used to exit the loop prematurely?": "B",
    "What is the output of: 4 > 2 or 3 < 1?": "A",
    "Which of the following is a correct syntax for 'if' condition?": "C",
    "Which keyword is used to start a loop in Python?": "A",
    "Which of these loops is entry-controlled?": "D",
    "What is the output of: not True and False?": "B",
    "Which of the following will result in an infinite loop?": "A",
    "Which statement is used to stop the current iteration and go to the next?": "D",
    "A loop inside another loop is called:": "C",
    "Which logical operator returns True only when both conditions are true?": "A",
    "Which loop is preferred when the number of iterations is unknown?": "B"
}

cs_ch6_mcq_options = {
    "Which statement is used for decision making in Python?": "A. if  B. loop  C. for  D. repeat",
    "Which of the following is not a valid conditional statement in Python?": "A. if  B. elif  C. elseif  D. else",
    "What is the keyword used for 'else if' in Python?": "A. ifelse  B. elif  C. elseif  D. ifelif",
    "What will 'if 0:' evaluate to?": "A. Error  B. True  C. False  D. None",
    "Which loop in Python is used when the number of iterations is known?": "A. while  B. repeat  C. switch  D. for",
    "What is the output of: print(5 > 3 and 4 < 2)?": "A. True  B. False  C. Error  D. None",
    "Which of the following is a valid loop in Python?": "A. for i in range(5):  B. loop i in range(5):  C. repeat 5 times:  D. run 5",
    "Which of the following will execute a loop 5 times?": "A. for i in 1 to 5  B. for(i=0; i<5; i++)  C. for i in range(5)  D. while i < 5",
    "Which statement is used to skip the rest of the loop and continue with next iteration?": "A. pass  B. break  C. stop  D. continue",
    "Which statement is used to exit the loop prematurely?": "A. exit  B. break  C. continue  D. stop",
    "What is the output of: 4 > 2 or 3 < 1?": "A. True  B. False  C. Error  D. None",
    "Which of the following is a correct syntax for 'if' condition?": "A. if(x>5)  B. if x > 5 then  C. if x > 5:  D. if x > 5",
    "Which keyword is used to start a loop in Python?": "A. for  B. repeat  C. run  D. select",
    "Which of these loops is entry-controlled?": "A. repeat-until  B. do-while  C. until  D. while",
    "What is the output of: not True and False?": "A. True  B. False  C. Error  D. None",
    "Which of the following will result in an infinite loop?": "A. while True:  B. for i in range(5):  C. if x==1:  D. break",
    "Which statement is used to stop the current iteration and go to the next?": "A. exit  B. stop  C. break  D. continue",
    "A loop inside another loop is called:": "A. dual loop  B. infinite loop  C. nested loop  D. sub loop",
    "Which logical operator returns True only when both conditions are true?": "A. and  B. or  C. not  D. xor",
    "Which loop is preferred when the number of iterations is unknown?": "A. for  B. while  C. repeat  D. switch"
}

true_false_cs_ch6 = {
    "The 'if' statement is used for decision making in Python.": "T",
    "Python uses 'elseif' instead of 'elif'.": "F",
    "A 'while' loop is used when the number of iterations is unknown.": "T",
    "The 'for' loop is used when the number of iterations is known.": "T",
    "The 'break' statement skips to the next iteration.": "F",
    "The 'continue' statement stops the loop completely.": "F",
    "Logical operators in Python include and, or, and not.": "T",
    "'if 0:' in Python is treated as False.": "T",
    "'if 1:' in Python is treated as True.": "T",
    "Python supports nested loops.": "T",
    "The condition in a while loop is checked after executing the body.": "F",
    "An infinite loop never terminates unless broken manually.": "T",
    "'break' is used to exit from a loop.": "T",
    "Indentation is not necessary in control flow.": "F",
    "Python has a switch-case control structure.": "F",
    "An if-else ladder helps handle multiple conditions.": "T",
    "'not' is a logical operator in Python.": "T",
    "The else block of an if-else is optional.": "T",
    "You can use 'pass' as a placeholder in Python.": "T",
    "A for loop cannot be nested inside a while loop.": "F",
    "Python uses braces { } to define blocks of code.": "F",
    "while True: creates an infinite loop.": "T",
    "'==' is used to assign values in Python.": "F",
    "The range(3) generates values 0, 1, 2.": "T",
    "A loop that never ends is called a dead loop.": "T"
}
