cs_ch12_mcq_options = {
    "What is a string in Python?": "A) Sequence of characters    B) Whole numbers    C) Decimal values    D) Boolean values",
    "Which of the following is a valid string declaration?": "A) str = 'Hello'    B) str = Hello    C) str = 1234    D) str = @hello",
    "How are strings enclosed in Python?": "A) Double quotes only    B) Single quotes only    C) Both single and double quotes    D) None",
    "What is the output of len('Python')?": "A) 5    B) 6    C) 7    D) Error",
    "Which operator is used to concatenate strings?": "A) +    B) *    C) -    D) &",
    "What does 'Python'[1] return?": "A) P    B) y    C) t    D) Error",
    "Which method converts a string to lowercase?": "A) lower()    B) down()    C) small()    D) low()",
    "Which method removes whitespace from both ends of a string?": "A) strip()    B) trim()    C) remove()    D) cut()",
    "Which of the following is a string method?": "A) append()    B) lower()    C) pop()    D) remove()",
    "What is the result of 'abc' * 2?": "A) abcabc    B) abc2    C) Error    D) abc abc",
    "Which method replaces a part of the string?": "A) replace()    B) change()    C) swap()    D) cut()",
    "What will 'hello'.upper() return?": "A) hello    B) HELLO    C) Hello    D) error",
    "What is slicing in strings?": "A) Removing string    B) Copying string    C) Getting substring using index range    D) Capitalizing string",
    "What will 'abcde'[1:4] return?": "A) abc    B) bcd    C) bcde    D) abcd",
    "Which function is used to get ASCII of a character?": "A) char()    B) ord()    C) asc()    D) ascii()",
    "Which function converts ASCII to character?": "A) chr()    B) ord()    C) ascii()    D) asc()",
    "What does 'Python'.find('t') return?": "A) 2    B) 1    C) 3    D) 0",
    "Which method returns number of times a character appears?": "A) count()    B) number()    C) repeat()    D) total()",
    "What is the index of last character in 'Python'?": "A) 6    B) 5    C) -1    D) 0",
    "Which of these methods returns a new string with capitalized first letter?": "A) capitalize()    B) title()    C) capfirst()    D) upperfirst()",
    "Strings in Python are": "A) Mutable    B) Immutable    C) Static    D) Flexible",
    "Which of the following creates an empty string?": "A) ''    B) \"\"    C) str()    D) All of these",
    "Which method splits a string into a list?": "A) split()    B) divide()    C) break()    D) separate()",
    "What will 'hello world'.split() return?": "A) ['hello', 'world']    B) 'hello', 'world'    C) ['hello world']    D) Error",
    "Which method checks if all characters in string are digits?": "A) isdigit()    B) isnumeric()    C) isint()    D) isdigit",
    "Which method checks for all alphabets in string?": "A) isalpha()    B) isalphabet()    C) alphabet()    D) alpha()",
    "What is the output of '  hello  '.strip()?": "A) hello    B) '  hello  '    C) 'hello  '    D) '  hello'",
    "Which method checks if string ends with given suffix?": "A) endswith()    B) finish()    C) isend()    D) end()",
    "What will 'abc'.islower() return?": "A) True    B) False    C) abc    D) Error",
    "Which of the following will result in error?": "A) 'abc'[3]    B) 'abc'[2]    C) 'abc'[1]    D) 'abc'[0]"
}

cs_ch12_mcq_answers = {
    "What is a string in Python?": "A",
    "Which of the following is a valid string declaration?": "A",
    "How are strings enclosed in Python?": "C",
    "What is the output of len('Python')?": "B",
    "Which operator is used to concatenate strings?": "A",
    "What does 'Python'[1] return?": "B",
    "Which method converts a string to lowercase?": "A",
    "Which method removes whitespace from both ends of a string?": "A",
    "Which of the following is a string method?": "B",
    "What is the result of 'abc' * 2?": "A",
    "Which method replaces a part of the string?": "A",
    "What will 'hello'.upper() return?": "B",
    "What is slicing in strings?": "C",
    "What will 'abcde'[1:4] return?": "B",
    "Which function is used to get ASCII of a character?": "B",
    "Which function converts ASCII to character?": "A",
    "What does 'Python'.find('t') return?": "A",
    "Which method returns number of times a character appears?": "A",
    "What is the index of last character in 'Python'?": "B",
    "Which of these methods returns a new string with capitalized first letter?": "A",
    "Strings in Python are": "B",
    "Which of the following creates an empty string?": "D",
    "Which method splits a string into a list?": "A",
    "What will 'hello world'.split() return?": "A",
    "Which method checks if all characters in string are digits?": "A",
    "Which method checks for all alphabets in string?": "A",
    "What is the output of '  hello  '.strip()?": "A",
    "Which method checks if string ends with given suffix?": "A",
    "What will 'abc'.islower() return?": "A",
    "Which of the following will result in error?": "A"
}

true_false_cs_ch12 = {
    "Strings in Python are immutable.": "True",
    "Strings can be concatenated using + operator.": "True",
    "The len() function returns number of characters in a string.": "True",
    "Negative indexing is allowed in strings.": "True",
    "Strings can be modified by directly assigning to an index.": "False",
    "The strip() method removes characters from both ends.": "True",
    "The upper() method modifies the original string.": "False",
    "Slicing a string creates a new string.": "True",
    "The find() method returns -1 if substring not found.": "True",
    "isdigit() checks if the string has only numbers.": "True",
    "Strings are stored as a sequence of characters.": "True",
    "replace() modifies the string in place.": "False",
    "split() divides the string into a list.": "True",
    "You can multiply strings with integers.": "True",
    "You can divide strings using /.": "False",
    "The lower() method converts all letters to lowercase.": "True",
    "The title() method capitalizes each word.": "True",
    "String indexing starts at 1 in Python.": "False",
    "You can use for loop to iterate through string.": "True",
    "endswith() checks how a string starts.": "False",
    "startswith() is a valid string method.": "True",
    "String comparison is case-sensitive in Python.": "True",
    "isalnum() returns True if string has only letters and numbers.": "True",
    "Python strings allow multiline declarations.": "True",
    "Triple quotes can be used for multiline strings.": "True",
    "You can access string characters using index.": "True",
    "String methods return a new string.": "True",
    "String methods work only on strings.": "True",
    "capitalize() and upper() are same.": "False"
}
