# cs/cs_ch16.py

cs_ch16_mcq_answers = {
    "Which keyword is used for loops in Python?": "A",
    "Which loop in Python is used for definite iteration?": "B",
    "Which of the following is an entry-controlled loop?": "A",
    "What is the output of: for i in range(3): print(i)": "C",
    "Which keyword is used to skip an iteration in a loop?": "C",
    "What does the 'break' statement do in Python?": "B",
    "What is the output of: range(2,6)?": "D",
    "What is the default increment value in range()?": "B",
    "Which of the following creates an infinite loop?": "A",
    "Which function is used to generate a sequence of numbers in Python?": "C",
    "Which loop should be used when the number of iterations is unknown?": "D",
    "What happens if a while loop condition is always False?": "A",
    "Which keyword does nothing and is used as a placeholder?": "C",
    "Which of the following is valid syntax?": "A",
    "In a for loop, what does 'for i in range(5)' do?": "B",
    "What is the result of range(1, 10, 3)?": "D",
    "Which loop is evaluated before the block runs?": "A",
    "What will happen with while True: pass": "C",
    "What does the else block in loops execute?": "B",
    "How many times will this run? for i in range(2, 5):": "C",
    "Which statement stops the loop immediately?": "B",
    "What does range(0, 10, 2) return?": "A",
    "Which of the following is not a valid loop keyword?": "D",
    "Which statement is true about 'continue'?": "B",
    "What will this print? for i in range(1): print(i)": "D",
    "Where can pass be used in a loop?": "A"
}

cs_ch16_mcq_options = {
    "Which keyword is used for loops in Python?": "A. for  B. loop  C. repeat  D. next",
    "Which loop in Python is used for definite iteration?": "A. while  B. for  C. do while  D. switch",
    "Which of the following is an entry-controlled loop?": "A. for  B. repeat  C. do-while  D. None",
    "What is the output of: for i in range(3): print(i)": "A. 1 2 3  B. 0 1 2 3  C. 0 1 2  D. Error",
    "Which keyword is used to skip an iteration in a loop?": "A. skip  B. pass  C. continue  D. skipline",
    "What does the 'break' statement do in Python?": "A. Skips current iteration  B. Exits the loop  C. Repeats the loop  D. Does nothing",
    "What is the output of: range(2,6)?": "A. [2,3,4,5,6]  B. [2,3,4,5,6,7]  C. [2,3,4,5,6,7,8]  D. [2,3,4,5]",
    "What is the default increment value in range()?": "A. 2  B. 1  C. 0  D. None",
    "Which of the following creates an infinite loop?": "A. while True:  B. for i in range(0):  C. if x==5:  D. pass",
    "Which function is used to generate a sequence of numbers in Python?": "A. numbers()  B. list()  C. range()  D. sequence()",
    "Which loop should be used when the number of iterations is unknown?": "A. for  B. switch  C. loop  D. while",
    "What happens if a while loop condition is always False?": "A. Loop doesn’t execute  B. Infinite loop  C. Error  D. None",
    "Which keyword does nothing and is used as a placeholder?": "A. break  B. continue  C. pass  D. None",
    "Which of the following is valid syntax?": "A. while x < 5:  B. while (x<5)  C. while x < 5  D. while x=5:",
    "In a for loop, what does 'for i in range(5)' do?": "A. Repeats 4 times  B. Repeats 5 times  C. Error  D. 6 times",
    "What is the result of range(1, 10, 3)?": "A. [1,2,3,...]  B. [1,4,7,10]  C. [1,4,7,10,13]  D. [1,4,7]",
    "Which loop is evaluated before the block runs?": "A. while  B. do while  C. forever  D. after",
    "What will happen with while True: pass": "A. error  B. print True  C. infinite loop  D. syntax error",
    "What does the else block in loops execute?": "A. Always  B. Only if no break occurs  C. Before loop  D. Only in if",
    "How many times will this run? for i in range(2, 5):": "A. 4  B. 5  C. 3  D. 2",
    "Which statement stops the loop immediately?": "A. continue  B. break  C. stop  D. return",
    "What does range(0, 10, 2) return?": "A. [0,2,4,6,8]  B. [0,2,4,6,8,10]  C. [2,4,6,8]  D. [0,1,2,3,...]",
    "Which of the following is not a valid loop keyword?": "A. break  B. continue  C. pass  D. skip",
    "Which statement is true about 'continue'?": "A. Terminates loop  B. Skips to next iteration  C. Restarts loop  D. Stops program",
    "What will this print? for i in range(1): print(i)": "A. Nothing  B. Error  C. 1  D. 0",
    "Where can pass be used in a loop?": "A. Anywhere  B. Only at end  C. Before break  D. After continue"
}

true_false_cs_ch16 = {
    "The for loop is used for definite iteration.": "T",
    "A while loop may run indefinitely if condition is always True.": "T",
    "The break statement terminates the loop.": "T",
    "continue skips the next iteration of the loop.": "F",
    "range(5) generates numbers from 0 to 5 inclusive.": "F",
    "range(1,5) includes number 5.": "F",
    "while True: creates an infinite loop.": "T",
    "pass can be used as a placeholder.": "T",
    "A loop must always have a break or continue.": "F",
    "Python does not support do-while loops.": "T",
    "The else block in a loop executes only if loop completes normally.": "T",
    "range(2, 10, 2) gives even numbers.": "T",
    "The step value in range can be negative.": "T",
    "break and continue can be used in for and while loops.": "T",
    "range() function cannot generate decreasing sequences.": "F",
    "continue ends the entire loop.": "F",
    "range(0,0) generates an empty sequence.": "T",
    "The for loop must always use range.": "F",
    "pass causes a syntax error in a loop.": "F",
    "while False: runs once.": "F",
    "range(0,6,2) gives 0,2,4.": "T",
    "You can use for loop to iterate over strings.": "T",
    "continue skips to the next iteration.": "T",
    "A loop may have both break and continue inside it.": "T",
    "range(1,1) is not a valid range.": "F",
    "range(1,4,0) will cause an error.": "T"
}