# cs/cs_ch13.py

cs_ch13_mcq_answers = {
    "Which statement is used for decision-making in Python?": "A",
    "Which of these is a valid Python if statement?": "C",
    "What is the output of: if 5 > 2: print('Yes')": "B",
    "Which keyword is used for an alternate condition in Python?": "A",
    "Which keyword is used to execute a block if condition is false?": "D",
    "How do you start an if block in Python?": "C",
    "What is the output of: if 3 == 3: print('True')": "A",
    "What does the elif keyword represent?": "C",
    "Which loop is best for a known number of iterations?": "B",
    "Which keyword is used to skip the rest of the loop?": "C",
    "Which keyword is used to exit a loop early?": "D",
    "What is the default step in range(5)?": "B",
    "How many times will the loop run: for i in range(3):": "C",
    "Which of the following is an infinite loop?": "A",
    "Which function is used to iterate over a sequence of numbers?": "B",
    "What is the output of range(1, 5)?": "C",
    "Which loop checks the condition before executing?": "A",
    "What is printed by: while False: print('Hi')": "D",
    "Which of these is NOT a loop control statement?": "D",
    "Where is the else clause used in loops?": "A",
    "What will print(range(3)) output?": "B",
    "Which of these evaluates a Boolean expression?": "A",
    "What is the output of: if 'a' in 'apple': print('Yes')": "C",
    "Which statement will execute no matter what in try-except-finally?": "D",
    "What is indentation used for in Python control flow?": "B",
    "What type of loop is while?": "A"
}

cs_ch13_mcq_options = {
    "Which statement is used for decision-making in Python?": "A. if  B. for  C. switch  D. match",
    "Which of these is a valid Python if statement?": "A. if (x > y) then:  B. if x > y then:  C. if x > y:  D. if > x y:",
    "What is the output of: if 5 > 2: print('Yes')": "A. Error  B. Yes  C. 5 > 2  D. True",
    "Which keyword is used for an alternate condition in Python?": "A. elif  B. elseif  C. else if  D. alternate",
    "Which keyword is used to execute a block if condition is false?": "A. if  B. elif  C. pass  D. else",
    "How do you start an if block in Python?": "A. if():  B. if {}  C. if condition:  D. if ->",
    "What is the output of: if 3 == 3: print('True')": "A. True  B. False  C. Error  D. None",
    "What does the elif keyword represent?": "A. Loop start  B. False block  C. Else if  D. Break condition",
    "Which loop is best for a known number of iterations?": "A. while  B. for  C. do while  D. if",
    "Which keyword is used to skip the rest of the loop?": "A. pass  B. stop  C. continue  D. skip",
    "Which keyword is used to exit a loop early?": "A. stop  B. exit  C. return  D. break",
    "What is the default step in range(5)?": "A. 2  B. 1  C. 0  D. undefined",
    "How many times will the loop run: for i in range(3):": "A. 0  B. 2  C. 3  D. Infinite",
    "Which of the following is an infinite loop?": "A. while True:  B. for i in range(0)  C. if x > 0:  D. while False:",
    "Which function is used to iterate over a sequence of numbers?": "A. list()  B. range()  C. len()  D. iter()",
    "What is the output of range(1, 5)?": "A. 1,5  B. [1,2,3,4,5]  C. [1,2,3,4]  D. [2,3,4,5]",
    "Which loop checks the condition before executing?": "A. while  B. do while  C. for  D. repeat",
    "What is printed by: while False: print('Hi')": "A. Hi  B. Error  C. False  D. Nothing",
    "Which of these is NOT a loop control statement?": "A. break  B. continue  C. pass  D. stop",
    "Where is the else clause used in loops?": "A. After the loop ends without break  B. Always  C. Before break  D. Only in if",
    "What will print(range(3)) output?": "A. [0,1,2]  B. range(0, 3)  C. (0,1,2)  D. error",
    "Which of these evaluates a Boolean expression?": "A. if  B. for  C. range  D. return",
    "What is the output of: if 'a' in 'apple': print('Yes')": "A. False  B. Error  C. Yes  D. a",
    "Which statement will execute no matter what in try-except-finally?": "A. except  B. break  C. else  D. finally",
    "What is indentation used for in Python control flow?": "A. Formatting  B. Block definition  C. Output  D. Return",
    "What type of loop is while?": "A. Entry-controlled  B. Counter-controlled  C. Object loop  D. Manual loop"
}

true_false_cs_ch13 = {
    "The 'if' statement is used for decision making.": "T",
    "Python has a switch-case statement like C/C++.": "F",
    "The 'else' block is optional in an if-else statement.": "T",
    "The elif statement must be followed by an else block.": "F",
    "The indentation level in Python defines blocks of code.": "T",
    "The for loop in Python is used only with numbers.": "F",
    "The range function includes the stop value.": "F",
    "The break statement skips one iteration of the loop.": "F",
    "The continue statement skips the current iteration.": "T",
    "The pass statement does nothing.": "T",
    "A while loop runs as long as the condition is true.": "T",
    "An infinite loop will eventually stop automatically.": "F",
    "Python supports both while and for loops.": "T",
    "A for loop can iterate over a string.": "T",
    "Indentation is not necessary in if-else blocks.": "F",
    "The else block in a loop executes only if loop ends normally.": "T",
    "The range(5) gives values from 1 to 5.": "F",
    "Python evaluates conditions using Boolean logic.": "T",
    "There is a do-while loop in Python.": "F",
    "You can use break in both for and while loops.": "T",
    "The continue statement can be used outside loops.": "F",
    "The '==' operator is used to compare two values.": "T",
    "The 'in' keyword can check if a value exists in a list.": "T",
    "A block with only 'pass' does not raise an error.": "T",
    "You can use else with a while loop.": "T",
    "The condition in a while loop is checked after running the loop once.": "F"
}
