# cs/cs_ch5.py

cs_ch5_mcq_answers = {
    "Python was developed by:": "A",
    "Python is a:": "C",
    "Which symbol is used to start a comment in Python?": "B",
    "Which of the following is a valid identifier in Python?": "A",
    "Which of the following is NOT a keyword in Python?": "D",
    "What is the extension of Python files?": "B",
    "Which function is used to take input from user?": "C",
    "What is the output of: print(3 + 2 * 2)?": "A",
    "What will be the output of: print('3' + '2')?": "C",
    "Which function is used to display output?": "A",
    "Python uses which type of typing?": "D",
    "Which of these is a data type in Python?": "B",
    "Which of the following is used to define a block in Python?": "C",
    "What is the result of 10 // 3?": "D",
    "Which function converts a string to an integer?": "B",
    "Which of these is an invalid variable name?": "C",
    "Which symbol is used for exponentiation in Python?": "A",
    "Which operator is used for remainder in Python?": "B",
    "Which of these is a logical operator?": "C",
    "Which of these can be used to represent strings in Python?": "D"
}

cs_ch5_mcq_options = {
    "Python was developed by:": "A. Guido van Rossum  B. Dennis Ritchie  C. James Gosling  D. Bjarne Stroustrup",
    "Python is a:": "A. low-level language  B. markup language  C. high-level language  D. assembly language",
    "Which symbol is used to start a comment in Python?": "A. //  B. #  C. <!--  D. @",
    "Which of the following is a valid identifier in Python?": "A. total_sum  B. 1stvalue  C. my-var  D. None of these",
    "Which of the following is NOT a keyword in Python?": "A. for  B. while  C. if  D. loop",
    "What is the extension of Python files?": "A. .java  B. .py  C. .txt  D. .exe",
    "Which function is used to take input from user?": "A. get()  B. scan()  C. input()  D. read()",
    "What is the output of: print(3 + 2 * 2)?": "A. 7  B. 10  C. 9  D. 5",
    "What will be the output of: print('3' + '2')?": "A. 6  B. 32  C. '32'  D. Error",
    "Which function is used to display output?": "A. print()  B. display()  C. echo()  D. show()",
    "Python uses which type of typing?": "A. Manual typing  B. Static typing  C. Explicit typing  D. Dynamic typing",
    "Which of these is a data type in Python?": "A. real  B. float  C. decimal  D. num",
    "Which of the following is used to define a block in Python?": "A. Curly braces  B. Semicolon  C. Indentation  D. Quotes",
    "What is the result of 10 // 3?": "A. 3.33  B. 3.0  C. 4  D. 3",
    "Which function converts a string to an integer?": "A. float()  B. int()  C. str()  D. bool()",
    "Which of these is an invalid variable name?": "A. my_var  B. var123  C. 123var  D. _value",
    "Which symbol is used for exponentiation in Python?": "A. **  B. ^  C. ^^  D. exp",
    "Which operator is used for remainder in Python?": "A. /  B. %  C. //  D. mod",
    "Which of these is a logical operator?": "A. ==  B. !=  C. and  D. &",
    "Which of these can be used to represent strings in Python?": "A. Double quotes  B. Single quotes  C. Triple quotes  D. All of these"
}

true_false_cs_ch5 = {
    "Python is a case-sensitive language.": "T",
    "The 'input()' function always returns an integer.": "F",
    "Variables in Python need to be declared with their data type.": "F",
    "Python uses indentation to define blocks of code.": "T",
    "The result of 3 + 2 * 2 is 10.": "F",
    "'3' + '2' will give '32' in Python.": "T",
    "Comments in Python are written using # symbol.": "T",
    "Python allows variable names to start with numbers.": "F",
    "print() is used to take input in Python.": "F",
    "Identifiers can include underscores in Python.": "T",
    "Python is compiled before running.": "F",
    "The keyword 'def' is used to define functions.": "T",
    "int('123') will convert string to integer.": "T",
    "Logical AND is written as 'and' in Python.": "T",
    "Python does not support real numbers.": "F",
    "The exponentiation operator in Python is ^.": "F",
    "input() returns a string by default.": "T",
    "0.1 + 0.2 == 0.3 is always true in Python.": "F",
    "Variables can be reassigned with different data types in Python.": "T",
    "Indentation errors cause syntax errors in Python.": "T",
    "Python programs must have a main function.": "F",
    "Boolean values in Python are True and False.": "T",
    "Strings can be written in single or double quotes.": "T",
    "print('Hello') and print( " + '"' + "Hello" + '"' ") will give different results.": "F",
    "Python files are saved with .py extension.": "T"
}
