# cs/cs_ch2.py

cs_ch3_mcq_answers = {
    "Which of the following is a basic logic gate?": "A",
    "Which gate gives a HIGH output only when both inputs are HIGH?": "B",
    "Which gate gives a LOW output only when both inputs are HIGH?": "C",
    "Which logic gate performs the NOT operation?": "D",
    "What is the output of AND gate with inputs 1 and 0?": "B",
    "What is the output of OR gate with inputs 0 and 0?": "C",
    "Which gate inverts the input?": "D",
    "What is the result of NOT(1)?": "B",
    "Which gate gives 1 only when inputs are different?": "C",
    "Boolean algebra is used in which field?": "A",
    "Which of the following is a universal gate?": "B",
    "Which of the following is also a universal gate?": "D",
    "How many input combinations does a 2-input gate have?": "C",
    "What does the XOR gate output for inputs 1 and 1?": "B",
    "Which gate is known as the inverter?": "D",
    "What is the result of 1 AND 1?": "A",
    "What is the result of 1 OR 0?": "C",
    "What is the result of NOT 0?": "D",
    "Which gate is used to construct any other logic gate?": "B",
    "Which gate outputs 1 when at least one input is 1?": "C",
    "Which gate outputs 0 when both inputs are 1?": "C",
    "Boolean logic uses which two constants?": "A",
    "Which logic operation is represented by ‘+’ in Boolean algebra?": "C",
    "Which logic operation is represented by ‘.’ in Boolean algebra?": "B",
    "Which of the following statements is true?": "D"
}

cs_ch3_mcq_options = {
    "Which of the following is a basic logic gate?": "A. AND  B. NAND  C. XOR  D. XNOR",
    "Which gate gives a HIGH output only when both inputs are HIGH?": "A. OR  B. AND  C. XOR  D. NOT",
    "Which gate gives a LOW output only when both inputs are HIGH?": "A. NOR  B. XOR  C. NAND  D. AND",
    "Which logic gate performs the NOT operation?": "A. AND  B. OR  C. NAND  D. NOT",
    "What is the output of AND gate with inputs 1 and 0?": "A. 1  B. 0  C. Undefined  D. None",
    "What is the output of OR gate with inputs 0 and 0?": "A. 1  B. Undefined  C. 0  D. None",
    "Which gate inverts the input?": "A. AND  B. OR  C. NAND  D. NOT",
    "What is the result of NOT(1)?": "A. 1  B. 0  C. Undefined  D. None",
    "Which gate gives 1 only when inputs are different?": "A. AND  B. NOR  C. XOR  D. NAND",
    "Boolean algebra is used in which field?": "A. Digital Electronics  B. Biology  C. Chemistry  D. Economics",
    "Which of the following is a universal gate?": "A. OR  B. NAND  C. XOR  D. NOT",
    "Which of the following is also a universal gate?": "A. OR  B. AND  C. XOR  D. NOR",
    "How many input combinations does a 2-input gate have?": "A. 2  B. 3  C. 4  D. 5",
    "What does the XOR gate output for inputs 1 and 1?": "A. 1  B. 0  C. Undefined  D. None",
    "Which gate is known as the inverter?": "A. AND  B. OR  C. NAND  D. NOT",
    "What is the result of 1 AND 1?": "A. 1  B. 0  C. Undefined  D. None",
    "What is the result of 1 OR 0?": "A. 0  B. 1  C. 1  D. 0",
    "What is the result of NOT 0?": "A. 0  B. Undefined  C. 1  D. 1",
    "Which gate is used to construct any other logic gate?": "A. OR  B. NAND  C. XOR  D. NOT",
    "Which gate outputs 1 when at least one input is 1?": "A. NAND  B. NOR  C. OR  D. AND",
    "Which gate outputs 0 when both inputs are 1?": "A. OR  B. NOT  C. NAND  D. XOR",
    "Boolean logic uses which two constants?": "A. 1 and 0  B. A and B  C. True and False  D. X and Y",
    "Which logic operation is represented by ‘+’ in Boolean algebra?": "A. NOT  B. XOR  C. OR  D. AND",
    "Which logic operation is represented by ‘.’ in Boolean algebra?": "A. OR  B. AND  C. NOT  D. XOR",
    "Which of the following statements is true?": "A. NOT gate has two inputs  B. AND outputs 1 for any input  C. OR gate inverts input  D. NAND is universal gate"
}

true_false_cs_ch3 = {
    "AND gate outputs 1 only when both inputs are 1.": "T",
    "OR gate outputs 0 only when both inputs are 1.": "F",
    "NOT gate is also called an inverter.": "T",
    "NAND is a combination of AND and NOT.": "T",
    "The output of XOR gate is 1 when both inputs are same.": "F",
    "Boolean algebra deals with binary values.": "T",
    "NOT gate can have two inputs.": "F",
    "OR gate outputs 0 if all inputs are 0.": "T",
    "A universal gate can be used to create any logic gate.": "T",
    "NOR is a combination of OR and NOT gates.": "T",
    "XOR gate outputs 1 only when inputs are different.": "T",
    "AND gate always outputs 0.": "F",
    "There are three basic gates: AND, OR, NOT.": "T",
    "NAND gate always gives 0 output.": "F",
    "XOR and XNOR are basic gates.": "F",
    "Boolean constants are only 0 and 1.": "T",
    "0 + 1 in Boolean is equal to 1.": "T",
    "1 · 1 in Boolean is equal to 1.": "T",
    "NOT 0 equals 1.": "T",
    "1 + 1 = 2 in Boolean logic.": "F",
    "XOR outputs 0 when inputs are the same.": "T",
    "AND gate has only one input.": "F",
    "NOT gate is a universal gate.": "F",
    "NOR gate outputs 1 if either input is 1.": "F",
    "Boolean algebra uses algebraic symbols to represent logic.": "T"
}