# cs/cs_ch10.py

cs_ch10_mcq_answers = {
    "Which of the following is used to include a module in Python?": "B",
    "Which keyword is used to import a module in Python?": "A",
    "Which of these modules is built-in in Python?": "D",
    "What does the math module provide?": "C",
    "Which of the following is the correct syntax to access the pi constant from the math module?": "A",
    "Which function returns the square root of a number?": "B",
    "What is the output of random.randint(1, 5)?": "D",
    "Which function from math module returns the absolute value?": "C",
    "Which function can be used to round down a number in math module?": "B",
    "The random module is used to:": "A",
    "Which statement is correct to import only sqrt from math module?": "C",
    "What will be the output of math.ceil(3.2)?": "D",
    "To generate a random float between 0 and 1, we use:": "A",
    "What does math.pow(2, 3) return?": "B",
    "Which module is used for mathematical operations in Python?": "C",
    "Which module is required to generate random numbers?": "A",
    "Which function returns the highest integer less than or equal to a number?": "D",
    "Which import is used to access all items from a module directly?": "B",
    "Which of the following is not a valid Python module?": "C",
    "Which module helps in working with date and time?": "D",
    "What does the function math.trunc(4.7) return?": "B",
    "Which function returns the smallest integer greater than or equal to a number?": "A",
    "Which of the following is a user-defined module?": "C",
    "Which built-in function lists all functions in a module?": "D",
    "What will math.fabs(-4.5) return?": "B",
    "Which of these is not a method in random module?": "C"
}

cs_ch10_mcq_options = {
    "Which of the following is used to include a module in Python?": "A. include  B. import  C. require  D. module",
    "Which keyword is used to import a module in Python?": "A. import  B. use  C. include  D. get",
    "Which of these modules is built-in in Python?": "A. numpy  B. tkinter  C. pandas  D. math",
    "What does the math module provide?": "A. File handling tools  B. OS-related functions  C. Mathematical functions  D. Random functions",
    "Which of the following is the correct syntax to access the pi constant from the math module?": "A. math.pi  B. pi  C. math:pi  D. get.pi",
    "Which function returns the square root of a number?": "A. pow()  B. sqrt()  C. root()  D. squareroot()",
    "What is the output of random.randint(1, 5)?": "A. 5.0  B. Any float from 1 to 5  C. Always 5  D. Random integer from 1 to 5",
    "Which function from math module returns the absolute value?": "A. round()  B. ceil()  C. fabs()  D. abs()",
    "Which function can be used to round down a number in math module?": "A. ceil()  B. floor()  C. trunc()  D. round()",
    "The random module is used to:": "A. Generate random numbers  B. Do math operations  C. Format strings  D. Work with loops",
    "Which statement is correct to import only sqrt from math module?": "A. import math.sqrt  B. use sqrt from math  C. from math import sqrt  D. from sqrt import math",
    "What will be the output of math.ceil(3.2)?": "A. 3.0  B. 3  C. 2  D. 4",
    "To generate a random float between 0 and 1, we use:": "A. random.random()  B. random.int()  C. random.range()  D. random.float()",
    "What does math.pow(2, 3) return?": "A. 6  B. 8.0  C. 8  D. 2³",
    "Which module is used for mathematical operations in Python?": "A. random  B. sys  C. math  D. os",
    "Which module is required to generate random numbers?": "A. random  B. math  C. os  D. numbers",
    "Which function returns the highest integer less than or equal to a number?": "A. ceil()  B. round()  C. trunc()  D. floor()",
    "Which import is used to access all items from a module directly?": "A. import math.all  B. from math import *  C. include math.*  D. math import all",
    "Which of the following is not a valid Python module?": "A. math  B. random  C. stringz  D. os",
    "Which module helps in working with date and time?": "A. timekeeper  B. clock  C. calendar  D. datetime",
    "What does the function math.trunc(4.7) return?": "A. 5  B. 4  C. 4.0  D. 5.0",
    "Which function returns the smallest integer greater than or equal to a number?": "A. ceil()  B. floor()  C. round()  D. int()",
    "Which of the following is a user-defined module?": "A. math  B. random  C. mymodule.py  D. string",
    "Which built-in function lists all functions in a module?": "A. list()  B. help()  C. print()  D. dir()",
    "What will math.fabs(-4.5) return?": "A. -4.5  B. 4.5  C. Error  D. 0",
    "Which of these is not a method in random module?": "A. randint()  B. random()  C. average()  D. choice()"
}

true_false_cs_ch10 = {
    "Python modules help organize code into reusable parts.": "T",
    "We use 'import' to bring a module into a program.": "T",
    "The math module includes functions like sqrt() and pow().": "T",
    "You need to install the math module before using it.": "F",
    "random.randint(1, 3) may return 1, 2 or 3.": "T",
    "Modules in Python can be built-in or user-defined.": "T",
    "The ceil() function rounds a number down.": "F",
    "from math import * lets you use all functions directly.": "T",
    "Modules reduce code duplication.": "T",
    "fabs() returns the absolute value of a number.": "T",
    "random.random() generates an integer between 0 and 1.": "F",
    "The 'import' statement must be used at the start of a file.": "F",
    "You can create your own modules in Python.": "T",
    "math.floor(4.9) returns 5.": "F",
    "Modules cannot contain functions.": "F",
    "math.pow() always returns an integer.": "F",
    "You can import multiple modules in one line.": "T",
    "datetime is used for drawing in Python.": "F",
    "A module is a file with Python definitions.": "T",
    "The keyword 'use' is used to import modules in Python.": "F",
    "Built-in modules are part of the Python Standard Library.": "T",
    "The round() function belongs to the math module.": "F",
    "You can use help(math) to see available functions.": "T",
    "The os module is used to perform OS-level operations.": "T",
    "User-defined modules must be saved with .txt extension.": "F",
    "random.choice() returns a random item from a list.": "T"
}
