cs_ch11_mcq_options = {
    "What is a list in Python?": "A) Mutable sequence    B) Immutable sequence    C) Dictionary    D) Tuple",
    "Which symbol is used to define a list?": "A) {}    B) ()    C) []    D) <>",
    "What will be the output of: len([1,2,3])?": "A) 1    B) 2    C) 3    D) Error",
    "What does list.append(x) do?": "A) Deletes x    B) Adds x at end    C) Adds x at start    D) Inserts x randomly",
    "Which method removes an item from the list?": "A) remove()    B) pop()    C) delete()    D) discard()",
    "What is the result of: [1,2,3] + [4,5]?": "A) [1,2,3,4,5]    B) [5,7,8]    C) Error    D) [1,2,3]+[4,5]",
    "Which index represents the first element in a list?": "A) 0    B) 1    C) -1    D) 2",
    "Which index accesses the last element of a list?": "A) -1    B) 0    C) len(list)    D) 1",
    "What is the output of: [3,4,5][1]?": "A) 3    B) 4    C) 5    D) 1",
    "What does list.pop() do?": "A) Deletes last item    B) Deletes first item    C) Adds last item    D) Removes specific item",
    "Which method inserts an element at a given position?": "A) insert()    B) append()    C) add()    D) include()",
    "What is the result of: list(range(3))?": "A) [1,2,3]    B) [0,1,2]    C) [0,1,2,3]    D) Error",
    "What is the type of [1,2,3]?": "A) list    B) tuple    C) dict    D) set",
    "How do you create an empty list?": "A) list()    B) []    C) both A and B    D) {}",
    "Which method reverses a list in place?": "A) reverse()    B) rev()    C) flip()    D) invert()",
    "What does list.clear() do?": "A) Deletes the list    B) Clears list items    C) Copies list    D) Reverses list",
    "Which of these can a list hold?": "A) integers    B) strings    C) lists    D) all of these",
    "What is list slicing?": "A) Getting list items using index range    B) Adding lists    C) Deleting list    D) Copying list",
    "Which method returns the index of an element?": "A) find()    B) index()    C) position()    D) search()",
    "What will [1,2,3]*2 give?": "A) [2,4,6]    B) [1,2,3,1,2,3]    C) Error    D) [6]",
    "Which of the following creates a list with 3 elements?": "A) [1,2,3]    B) list(3)    C) (1,2,3)    D) {1,2,3}",
    "What will [1,2,3].count(2) return?": "A) 0    B) 1    C) 2    D) Error",
    "How do you check if 5 is in list1?": "A) 5 in list1    B) list1.has(5)    C) list1.find(5)    D) exists(list1,5)",
    "What is the output of list(range(2,6))?": "A) [2,3,4,5]    B) [2,3,4,5,6]    C) [3,4,5,6]    D) Error",
    "Which function returns sorted copy of a list?": "A) sort()    B) sorted()    C) reverse()    D) order()",
    "What does list1[:] return?": "A) Sublist    B) New copy of list    C) Nothing    D) Error",
    "Which of the following modifies the original list?": "A) sorted()    B) slice()    C) sort()    D) list()",
    "Which list operation copies a list?": "A) list2 = list1[:]    B) list2 = list1    C) list2.copy(list1)    D) list2 = copy(list1)",
    "What does list.extend([x,y]) do?": "A) Adds x and y as sublist    B) Adds each element separately    C) Deletes x and y    D) Overwrites list",
    "Which of the following is correct about lists?": "A) Lists can grow and shrink    B) Lists are immutable    C) List keys must be strings    D) List values are fixed"
}

cs_ch11_mcq_answers = {
    "What is a list in Python?": "A",
    "Which symbol is used to define a list?": "C",
    "What will be the output of: len([1,2,3])?": "C",
    "What does list.append(x) do?": "B",
    "Which method removes an item from the list?": "A",
    "What is the result of: [1,2,3] + [4,5]?": "A",
    "Which index represents the first element in a list?": "A",
    "Which index accesses the last element of a list?": "A",
    "What is the output of: [3,4,5][1]?": "B",
    "What does list.pop() do?": "A",
    "Which method inserts an element at a given position?": "A",
    "What is the result of: list(range(3))?": "B",
    "What is the type of [1,2,3]?": "A",
    "How do you create an empty list?": "C",
    "Which method reverses a list in place?": "A",
    "What does list.clear() do?": "B",
    "Which of these can a list hold?": "D",
    "What is list slicing?": "A",
    "Which method returns the index of an element?": "B",
    "What will [1,2,3]*2 give?": "B",
    "Which of the following creates a list with 3 elements?": "A",
    "What will [1,2,3].count(2) return?": "B",
    "How do you check if 5 is in list1?": "A",
    "What is the output of list(range(2,6))?": "A",
    "Which function returns sorted copy of a list?": "B",
    "What does list1[:] return?": "B",
    "Which of the following modifies the original list?": "C",
    "Which list operation copies a list?": "A",
    "What does list.extend([x,y]) do?": "B",
    "Which of the following is correct about lists?": "A"
}

true_false_cs_ch11 = {
    "Lists are mutable.": "True",
    "Lists can store values of different data types.": "True",
    "Lists are defined using curly braces.": "False",
    "Indexing in lists starts at 1.": "False",
    "Negative indexing is allowed in Python lists.": "True",
    "The append() method adds an element to the end of the list.": "True",
    "The pop() method removes an element from the start of the list.": "False",
    "The insert() method can add an element at a specific index.": "True",
    "Lists cannot be sliced.": "False",
    "The len() function returns the number of items in a list.": "True",
    "The reverse() method modifies the original list.": "True",
    "Lists can contain duplicate values.": "True",
    "The sort() function returns a new sorted list.": "False",
    "The sorted() function sorts the list in-place.": "False",
    "The remove() method deletes the first matching item.": "True",
    "The clear() method deletes all items from the list.": "True",
    "List elements must be integers.": "False",
    "list[1:3] gives elements at index 1 and 2.": "True",
    "list[::2] skips every second element.": "True",
    "list1 = list2 copies values, not reference.": "False",
    "list1 == list2 compares reference not values.": "False",
    "list.copy() and list1[:] give the same result.": "True",
    "Lists can be used as stack using append and pop.": "True",
    "List comprehension is a method to create lists.": "True",
    "An empty list evaluates to False in a condition.": "True",
    "A list can store another list.": "True",
    "A list is also a sequence in Python.": "True",
    "You can use loops to iterate through a list.": "True",
    "Lists are immutable like strings.": "False"
}
