
true_false_cs_ch1 = {
    "A computer system consists of both hardware and software components.": "T",
    "ALU stands for Arithmetic Logic Utility.": "F",
    "The CPU is also known as the brain of the computer.": "T",
    "Input devices are used to display information to the user.": "F",
    "ROM is a type of non-volatile memory.": "T",
    "RAM retains its data even after the power is turned off.": "F",
    "A printer is an example of an output device.": "T",
    "Software is the physical component of a computer.": "F",
    "System software includes the operating system.": "T",
    "Microsoft Word is an example of system software.": "F",
    "Secondary storage devices are slower than primary memory.": "T",
    "Cache memory is larger and slower than RAM.": "F",
    "The control unit directs the operations of the processor.": "T",
    "BIOS stands for Basic Input Output System.": "T",
    "The mouse is a processing device.": "F",
    "SSD stands for Solid State Drive.": "T",
    "The power supply unit converts DC to AC.": "F",
    "Operating system is required to operate a computer.": "T",
    "Compiler translates high-level language to machine language.": "T",
    "Binary number system uses digits from 0 to 9.": "F",
    "The keyboard is used to input data into the computer.": "T",
    "Monitor is a type of input device.": "F",
    "Data and instructions are stored in the memory unit.": "T",
    "Assembly language is easier to understand than machine language.": "T",
    "Hard disk is a volatile memory.": "F",
    "Linux is an open-source operating system.": "T",
    "Hardware can function without software.": "F",
    "The speed of a computer is measured in GHz.": "T",
    "Application software controls basic hardware functions.": "F",
    "The CU (Control Unit) performs arithmetic operations.": "F",
    "EPROM can be erased and reprogrammed.": "T",
    "The booting process loads the operating system into RAM.": "T",
    "A scanner is used to convert paper documents into digital form.": "T",
    "The system unit contains the CPU, motherboard, and RAM.": "T",
    "A modem converts analog signals to digital and vice versa.": "T",
    "Machine language is written using mnemonics.": "F",
    "Software can be touched and physically handled.": "F",
    "ASCII is used to represent characters in binary form.": "T",
    "Byte is the smallest unit of memory.": "F",
    "All software is application software.": "F",
    "Input and output devices are part of hardware.": "T",
    "RAM is an example of primary memory.": "T",
    "Interpreter translates the entire program at once.": "F",
    "The main memory is slower than secondary storage.": "F",
    "Bit stands for binary digit.": "T",
    "ROM can be modified easily by the user.": "F",
    "The motherboard connects all components of a computer.": "T",
    "Computer systems only consist of software.": "F",
    "The operating system manages memory and processes.": "T",
    "A touchscreen functions as both input and output device.": "T"
}

# ch1_mcq.py

cs_ch1_mcq_answers = {
    "What is the brain of the computer system?": "C",
    "Which of these is a primary memory?": "A",
    "Which of the following is an output device?": "D",
    "What does ALU stand for?": "B",
    "Which memory is non-volatile?": "C",
    "Which of these is used for permanent storage?": "D",
    "Which component processes data and instructions?": "A",
    "Which part of the CPU controls all operations?": "B",
    "Which software manages the computer hardware?": "C",
    "Which of the following is not an input device?": "D",
    "Which of these is system software?": "B",
    "Which unit converts analog signals to digital?": "A",
    "Which of the following is a secondary storage device?": "C",
    "Which unit performs arithmetic and logical operations?": "B",
    "Which of these is not an example of software?": "D",
    "What is the full form of ROM?": "A",
    "Which device is used to connect a network?": "C",
    "Which memory is the fastest?": "B",
    "Which language is directly understood by a computer?": "D",
    "Which of these is volatile memory?": "A",
    "Which component temporarily stores data during processing?": "B",
    "Which of these translates high-level code to machine code?": "C",
    "Which memory is present on the CPU chip?": "D",
    "Which device lets you print hard copies?": "A",
    "Which is the correct sequence: Input -> Process -> Output -> ____?": "D"
}

cs_ch1_mcq_options = {
    "What is the brain of the computer system?": "A. RAM  B. ROM  C. CPU  D. SSD",
    "Which of these is a primary memory?": "A. RAM  B. Hard Disk  C. DVD  D. Pen Drive",
    "Which of the following is an output device?": "A. Mouse  B. Scanner  C. Keyboard  D. Monitor",
    "What does ALU stand for?": "A. Advanced Logic Unit  B. Arithmetic Logic Unit  C. Application Logic Unit  D. Automated Logic Unit",
    "Which memory is non-volatile?": "A. RAM  B. Cache  C. ROM  D. Registers",
    "Which of these is used for permanent storage?": "A. RAM  B. Cache  C. Registers  D. Hard Disk",
    "Which component processes data and instructions?": "A. CPU  B. SSD  C. RAM  D. Cache",
    "Which part of the CPU controls all operations?": "A. ALU  B. Control Unit  C. BIOS  D. Cache",
    "Which software manages the computer hardware?": "A. Compiler  B. Word Processor  C. Operating System  D. Game",
    "Which of the following is not an input device?": "A. Keyboard  B. Scanner  C. Microphone  D. Projector",
    "Which of these is system software?": "A. MS Word  B. Linux OS  C. Tally  D. PowerPoint",
    "Which unit converts analog signals to digital?": "A. Modem  B. CPU  C. RAM  D. Printer",
    "Which of the following is a secondary storage device?": "A. RAM  B. Cache  C. CD-ROM  D. Registers",
    "Which unit performs arithmetic and logical operations?": "A. Control Unit  B. ALU  C. Register  D. ROM",
    "Which of these is not an example of software?": "A. MS Word  B. Compiler  C. Windows  D. Scanner",
    "What is the full form of ROM?": "A. Read Only Memory  B. Random Ordered Memory  C. Read On Memory  D. Run Only Memory",
    "Which device is used to connect a network?": "A. USB  B. Printer  C. NIC  D. SSD",
    "Which memory is the fastest?": "A. RAM  B. Cache  C. SSD  D. CD-ROM",
    "Which language is directly understood by a computer?": "A. C++  B. Python  C. Assembly  D. Machine Language",
    "Which of these is volatile memory?": "A. RAM  B. ROM  C. SSD  D. DVD",
    "Which component temporarily stores data during processing?": "A. ALU  B. RAM  C. SSD  D. CD-ROM",
    "Which of these translates high-level code to machine code?": "A. OS  B. ROM  C. Compiler  D. Browser",
    "Which memory is present on the CPU chip?": "A. RAM  B. ROM  C. HDD  D. Cache",
    "Which device lets you print hard copies?": "A. Printer  B. Monitor  C. Speaker  D. Projector",
    "Which is the correct sequence: Input -> Process -> Output -> ____?": "A. Boot  B. BIOS  C. Operating System  D. Storage"
}