cs_ch9_mcq_options = {
    "Which statement is used to make decisions in Python?": "A) loop    B) switch    C) if    D) def",
    "Which keyword is used for multiple conditions in Python?": "A) elseif    B) elif    C) else if    D) ifelse",
    "What does an if statement evaluate?": "A) integer    B) string    C) boolean expression    D) list",
    "Which statement is optional in an if-else construct?": "A) if    B) else    C) elif    D) all are required",
    "Which of the following loops is not available in Python?": "A) for    B) do-while    C) while    D) nested for",
    "What is the output of: if 5 > 3: print('Yes')?": "A) No output    B) Yes    C) Error    D) False",
    "How many times will 'for i in range(3)' execute?": "A) 1    B) 2    C) 3    D) 4",
    "What is the use of range(5)?": "A) loops from 0 to 5    B) loops from 1 to 5    C) loops from 0 to 4    D) error",
    "What is the default increment in range()?": "A) 1    B) 0    C) 2    D) -1",
    "Which loop runs until a condition is false?": "A) for    B) do-while    C) while    D) infinite",
    "Which loop is used when the number of iterations is known?": "A) while    B) for    C) do-while    D) switch",
    "Which keyword is used to skip an iteration in a loop?": "A) skip    B) pass    C) continue    D) break",
    "Which keyword is used to exit a loop early?": "A) stop    B) end    C) break    D) return",
    "Which of the following is not a valid conditional operator?": "A) ==    B) =    C) >    D) <",
    "Which block executes when if condition is false?": "A) elif    B) if    C) else    D) for",
    "What does 'pass' keyword do?": "A) skips loop    B) exits loop    C) does nothing    D) repeats",
    "Which loop is best when you don't know how many times to repeat?": "A) for    B) while    C) do-while    D) nested",
    "What is the correct syntax for if-else?": "A) if () then {} else {}    B) if condition:    C) if {condition}:    D) if condition then",
    "What is the output of: for i in range(0): print(i)?": "A) 0    B) Error    C) None    D) No output",
    "Which function is used to terminate program execution?": "A) stop()    B) quit()    C) break()    D) end()",
    "Which keyword handles multiple decision branches?": "A) elif    B) while    C) case    D) loop",
    "When is 'else' in a loop used?": "A) when loop breaks    B) when loop ends normally    C) always    D) never",
    "What will 'while False:' do?": "A) infinite loop    B) syntax error    C) no output    D) prints False",
    "Which of the following is correct for infinite loop?": "A) while True:    B) while(1):    C) for i in range(1):    D) A and B",
    "What is the result of: 'if 0:'?": "A) True    B) False    C) Error    D) 0",
    "Which keyword is used to write a loop inside another loop?": "A) inner    B) loop    C) nested    D) No keyword",
    "Which operator is used to check multiple conditions?": "A) or    B) and    C) not    D) both A and B",
    "Which statement ends a loop completely?": "A) continue    B) break    C) pass    D) stop",
    "What is the result of: 'if not True:'?": "A) True block runs    B) False block runs    C) Nothing runs    D) Error",
    "What is the meaning of: 'if a != b:'?": "A) a equals b    B) a less than b    C) a not equals b    D) syntax error"
}

cs_ch9_mcq_answers = {
    "Which statement is used to make decisions in Python?": "C",
    "Which keyword is used for multiple conditions in Python?": "B",
    "What does an if statement evaluate?": "C",
    "Which statement is optional in an if-else construct?": "B",
    "Which of the following loops is not available in Python?": "B",
    "What is the output of: if 5 > 3: print('Yes')?": "B",
    "How many times will 'for i in range(3)' execute?": "C",
    "What is the use of range(5)?": "C",
    "What is the default increment in range()?": "A",
    "Which loop runs until a condition is false?": "C",
    "Which loop is used when the number of iterations is known?": "B",
    "Which keyword is used to skip an iteration in a loop?": "C",
    "Which keyword is used to exit a loop early?": "C",
    "Which of the following is not a valid conditional operator?": "B",
    "Which block executes when if condition is false?": "C",
    "What does 'pass' keyword do?": "C",
    "Which loop is best when you don't know how many times to repeat?": "B",
    "What is the correct syntax for if-else?": "B",
    "What is the output of: for i in range(0): print(i)?": "D",
    "Which function is used to terminate program execution?": "B",
    "Which keyword handles multiple decision branches?": "A",
    "When is 'else' in a loop used?": "B",
    "What will 'while False:' do?": "C",
    "Which of the following is correct for infinite loop?": "D",
    "What is the result of: 'if 0:'?": "B",
    "Which keyword is used to write a loop inside another loop?": "D",
    "Which operator is used to check multiple conditions?": "D",
    "Which statement ends a loop completely?": "B",
    "What is the result of: 'if not True:'?": "B",
    "What is the meaning of: 'if a != b:'?": "C"
}

true_false_cs_ch9 = {
    "An if statement always needs an else.": "False",
    "The 'elif' keyword is used for multiple conditions.": "True",
    "In a for loop, range(3) gives values 0, 1, 2.": "True",
    "The 'break' statement skips to next iteration.": "False",
    "The 'continue' statement skips current iteration.": "True",
    "The else block in a loop runs when loop ends normally.": "True",
    "'while False' runs infinitely.": "False",
    "The 'pass' keyword performs no operation.": "True",
    "'range(5)' gives 0 to 5 including 5.": "False",
    "'if' can be used without else or elif.": "True",
    "Python supports switch-case.": "False",
    "'not' is a logical operator.": "True",
    "'!=' means not equal to.": "True",
    "A loop inside another loop is called nested loop.": "True",
    "Python has 'do-while' loops.": "False",
    "'if 0:' executes the if block.": "False",
    "'while True:' creates an infinite loop.": "True",
    "You can use else with while loops.": "True",
    "The 'quit()' function exits the program.": "True",
    "'elif' can be used without if.": "False",
    "The 'break' exits the innermost loop.": "True",
    "'continue' ends the loop completely.": "False",
    "A single condition in if must return a boolean.": "True",
    "for i in range(0): runs once.": "False",
    "if 5 > 3: print('Yes') will print Yes.": "True",
    "Python allows nesting of if-else statements.": "True",
    "pass is used to handle errors.": "False",
    "An if block can be empty using pass.": "True",
    "for and while are both entry-controlled loops.": "True",
    "The loop body must be indented properly.": "True"
}
