cs_ch15_mcq_options = {
    "What are library functions in Python?": "A) Built-in functions provided by Python    B) User-defined functions    C) Functions from C language    D) Error handlers",
    "Which of these is a library function?": "A) print()    B) display()    C) input_data()    D) insert()",
    "What will abs(-4) return?": "A) 0    B) 4    C) -4    D) Error",
    "Which function returns the maximum value?": "A) max()    B) maxval()    C) top()    D) maximum()",
    "What does round(4.6) return?": "A) 4    B) 5    C) 6    D) Error",
    "Which function returns the smallest value in a sequence?": "A) min()    B) low()    C) least()    D) minimum()",
    "What does pow(2, 3) return?": "A) 6    B) 8    C) 9    D) 2^3",
    "What is the output of type(5)?": "A) int    B) <class 'int'>    C) number    D) integer",
    "Which function returns the Unicode code of a character?": "A) chr()    B) ord()    C) ascii()    D) code()",
    "What does chr(65) return?": "A) 65    B) 'A'    C) A    D) Error",
    "Which function returns square root in math module?": "A) sqrt()    B) squareroot()    C) root()    D) square()",
    "What is the output of round(5.49)?": "A) 5    B) 6    C) 5.5    D) Error",
    "What is the output of round(5.5)?": "A) 5    B) 6    C) 5.0    D) Error",
    "Which module must be imported to use math functions?": "A) math    B) sqrt    C) cmath    D) random",
    "What will type('hello') return?": "A) string    B) str    C) <class 'str'>    D) 'str'",
    "Which function returns random integers?": "A) randint()    B) rand()    C) randomint()    D) generate()",
    "What does help() function do?": "A) Displays documentation    B) Prints code    C) Saves file    D) Exits Python",
    "What is the output of max(3, 9, 5)?": "A) 3    B) 9    C) 5    D) Error",
    "What does len('Python') return?": "A) 5    B) 6    C) 7    D) 0",
    "Which of the following is not a built-in function?": "A) input()    B) append()    C) print()    D) type()",
    "Which function returns number of items in a sequence?": "A) len()    B) size()    C) count()    D) number()",
    "Which built-in function can convert string to integer?": "A) str()    B) int()    C) chr()    D) eval()",
    "What does float('4.5') return?": "A) 4.5    B) '4.5'    C) Error    D) int",
    "Which of the following is a type conversion function?": "A) int()    B) str()    C) float()    D) All of these",
    "What is output of int('8')?": "A) 8    B) '8'    C) Error    D) float",
    "What will min([2, 3, 1]) return?": "A) 3    B) 2    C) 1    D) 0",
    "Which function gives remainder of division?": "A) mod()    B) %    C) div()    D) rem()",
    "What does isinstance(3, int) return?": "A) True    B) False    C) int    D) None",
    "What does type(3.14) return?": "A) float    B) <class 'float'>    C) decimal    D) number",
    "Which of these functions can be used with strings?": "A) len()    B) min()    C) max()    D) All of these"
}

cs_ch15_mcq_answers = {
    "What are library functions in Python?": "A",
    "Which of these is a library function?": "A",
    "What will abs(-4) return?": "B",
    "Which function returns the maximum value?": "A",
    "What does round(4.6) return?": "B",
    "Which function returns the smallest value in a sequence?": "A",
    "What does pow(2, 3) return?": "B",
    "What is the output of type(5)?": "B",
    "Which function returns the Unicode code of a character?": "B",
    "What does chr(65) return?": "B",
    "Which function returns square root in math module?": "A",
    "What is the output of round(5.49)?": "A",
    "What is the output of round(5.5)?": "B",
    "Which module must be imported to use math functions?": "A",
    "What will type('hello') return?": "C",
    "Which function returns random integers?": "A",
    "What does help() function do?": "A",
    "What is the output of max(3, 9, 5)?": "B",
    "What does len('Python') return?": "B",
    "Which of the following is not a built-in function?": "B",
    "Which function returns number of items in a sequence?": "A",
    "Which built-in function can convert string to integer?": "B",
    "What does float('4.5') return?": "A",
    "Which of the following is a type conversion function?": "D",
    "What is output of int('8')?": "A",
    "What will min([2, 3, 1]) return?": "C",
    "Which function gives remainder of division?": "B",
    "What does isinstance(3, int) return?": "A",
    "What does type(3.14) return?": "B",
    "Which of these functions can be used with strings?": "D"
}

true_false_cs_ch15 = {
    "abs() returns the absolute value of a number.": "True",
    "round(2.9) returns 3.": "True",
    "type() returns the class type of object.": "True",
    "min() can only be used with integers.": "False",
    "max(4, 9) returns 9.": "True",
    "chr(66) returns 'B'.": "True",
    "ord('A') returns 65.": "True",
    "pow(2,3) is the same as 2**3.": "True",
    "math.sqrt(16) returns 4.": "True",
    "help() can be used to see documentation.": "True",
    "print() is a user-defined function.": "False",
    "input() is a built-in function.": "True",
    "len('abc') returns 3.": "True",
    "float('3.5') returns 3.5.": "True",
    "int('3.5') will not cause an error.": "False",
    "isinstance(3, int) returns True.": "True",
    "type(10.0) returns <class 'int'>.": "False",
    "round(5.5) returns 6.": "True",
    "max() can be used with strings.": "True",
    "len() only works with lists.": "False",
    "type('5') returns <class 'str'>.": "True",
    "min(['a', 'b', 'c']) returns 'a'.": "True",
    "type(True) returns <class 'bool'>.": "True",
    "chr(256) will raise an error.": "False",
    "pow(9, 0.5) returns 3.0.": "True",
    "abs(0) returns 1.": "False",
    "input() returns a string by default.": "True",
    "print() can take multiple arguments.": "True",
    "round() can accept two arguments.": "True"
}