# cs/cs_ch2.py

cs_ch2_mcq_answers = {
    "What is the base of the binary number system?": "A",
    "What is the base of the decimal number system?": "B",
    "How many digits are there in the binary system?": "C",
    "Which number system uses digits 0-9 and A-F?": "D",
    "What is 1010 (binary) in decimal?": "B",
    "What is 15 (decimal) in binary?": "C",
    "Which of the following is a valid hexadecimal number?": "D",
    "What is the binary equivalent of decimal 8?": "A",
    "Which code is used for character representation in computers?": "B",
    "Which code represents each digit of a decimal number separately in 4-bit binary?": "C",
    "Which of the following is not a number system?": "A",
    "Which is the smallest unit of data in a computer?": "B",
    "1 Byte = ? bits": "C",
    "What is the binary value of 2 in 4 bits?": "A",
    "Which number system is used internally by computers?": "C",
    "How many symbols does hexadecimal use?": "D",
    "What is the hexadecimal of binary 1101?": "B",
    "In ASCII, capital ‘A’ is represented by which decimal value?": "C",
    "BCD stands for:": "A",
    "Which code is commonly used in digital electronics?": "D"
}

cs_ch2_mcq_options = {
    "What is the base of the binary number system?": "A. 2  B. 8  C. 10  D. 16",
    "What is the base of the decimal number system?": "A. 2  B. 10  C. 8  D. 16",
    "How many digits are there in the binary system?": "A. 8  B. 4  C. 2  D. 10",
    "Which number system uses digits 0-9 and A-F?": "A. Binary  B. Octal  C. Decimal  D. Hexadecimal",
    "What is 1010 (binary) in decimal?": "A. 8  B. 10  C. 12  D. 14",
    "What is 15 (decimal) in binary?": "A. 1110  B. 1111  C. 1111  D. 1001",
    "Which of the following is a valid hexadecimal number?": "A. 128  B. 1G  C. Z9  D. 3A",
    "What is the binary equivalent of decimal 8?": "A. 1000  B. 1010  C. 1100  D. 0101",
    "Which code is used for character representation in computers?": "A. EBCDIC  B. ASCII  C. BCD  D. Gray",
    "Which code represents each digit of a decimal number separately in 4-bit binary?": "A. ASCII  B. Gray  C. BCD  D. Hex",
    "Which of the following is not a number system?": "A. Roman  B. Binary  C. Octal  D. Hexadecimal",
    "Which is the smallest unit of data in a computer?": "A. Byte  B. Bit  C. Word  D. Nibble",
    "1 Byte = ? bits": "A. 4  B. 6  C. 8  D. 16",
    "What is the binary value of 2 in 4 bits?": "A. 0010  B. 0101  C. 0001  D. 1111",
    "Which number system is used internally by computers?": "A. Octal  B. Decimal  C. Binary  D. Hexadecimal",
    "How many symbols does hexadecimal use?": "A. 2  B. 8  C. 10  D. 16",
    "What is the hexadecimal of binary 1101?": "A. C  B. D  C. E  D. F",
    "In ASCII, capital ‘A’ is represented by which decimal value?": "A. 64  B. 66  C. 65  D. 97",
    "BCD stands for:": "A. Binary Coded Decimal  B. Binary Counted Decimal  C. Basic Code Decimal  D. Binary Code Digit",
    "Which code is commonly used in digital electronics?": "A. EBCDIC  B. ASCII  C. Unicode  D. Gray"
}

true_false_cs_ch2 = {
    "Binary number system has base 2.": "T",
    "Decimal number system uses only digits 0 and 1.": "F",
    "Octal number system has base 8.": "T",
    "Hexadecimal numbers include letters A to F.": "T",
    "In binary, 10 means ten.": "F",
    "BCD represents each decimal digit in binary.": "T",
    "Gray code is used to reduce errors in digital systems.": "T",
    "1 Byte = 4 bits.": "F",
    "ASCII is used to represent numbers only.": "F",
    "Binary 1000 equals decimal 8.": "T",
    "Hexadecimal 1F equals binary 00011111.": "T",
    "Gray code is same as binary.": "F",
    "Computers use decimal system internally.": "F",
    "In ASCII, 'A' is 65.": "T",
    "BCD can store any decimal number in 4 bits.": "F",
    "Hexadecimal is base 10.": "F",
    "EBCDIC is a character encoding system.": "T",
    "Binary 1111 is decimal 15.": "T",
    "Octal system uses digits 0–7.": "T",
    "BCD stands for Binary Character Data.": "F",
    "In 8 bits, we can represent up to 256 values.": "T",
    "Unicode uses 7 bits for each character.": "F",
    "A nibble is 8 bits.": "F",
    "Decimal 9 in binary is 1001.": "T",
    "Binary system uses only two digits.": "T"
}