cs_ch7_mcq_options = {
    "Which of the following is a valid Boolean expression?": "A) True or True    B) False and True    C) True and False    D) False or False",
    "What is the result of: not (True and False)?": "A) not (True or False)    B) not True and False    C) not (True and False)    D) True and not False",
    "Which operator is used for logical negation?": "A) and    B) or    C) not    D) xor",
    "What does True and False evaluate to?": "A) False    B) True    C) Error    D) None",
    "What type of operator is 'and'?": "A) Logical operator    B) Bitwise operator    C) Assignment operator    D) Comparison operator",
    "Which of these is a correct logical operator in Python?": "A) not    B) !    C) and    D) or",
    "What is the output of: 5 > 6?": "A) True    B) False    C) None    D) Error",
    "Which set contains all Boolean operators?": "A) and, or, not    B) &, |, !    C) &&, ||, !    D) +, -, *",
    "Which operator is used to compare equality?": "A) ==    B) =    C) ===    D) equal",
    "What is the output of: 2 + 3 * 1?": "A) 5    B) 6    C) 7    D) Error",
    "What is the output of not False?": "A) True    B) False    C) Error    D) None",
    "Which of the following represents an invalid logical expression?": "A) True or False    B) not True    C) True xor False    D) False and True",
    "The result of True and not False is?": "A) True    B) False    C) Error    D) None",
    "Which one is not a logical operator?": "A) and    B) not    C) or    D) xor",
    "What is the data type of the expression (4 > 2)?": "A) int    B) str    C) bool    D) float",
    "True or False and not True evaluates to?": "A) True    B) False    C) Error    D) None",
    "What will be the result of 0 and 1?": "A) 1    B) 0    C) True    D) Error",
    "In Python, which of these values is treated as False?": "A) 0    B) 1    C) -1    D) 'False'",
    "Which of the following returns True?": "A) not (5 < 3)    B) 5 < 3 and 3 > 2    C) 3 > 4 or 2 > 5    D) False and False",
    "Which operator has the highest precedence?": "A) and    B) or    C) not    D) =",
    "not (True or False) evaluates to?": "A) True    B) False    C) Error    D) None",
    "What is the output of (3 < 5) and (5 > 2)?": "A) True    B) False    C) Error    D) None",
    "Which operator is used to represent inequality?": "A) !=    B) =!    C) ===    D) !==",
    "Boolean values are represented using which keywords in Python?": "A) TRUE/FALSE    B) True/False    C) true/false    D) T/F",
    "Logical operators return results of type?": "A) int    B) float    C) bool    D) str",
    "Which of the following is a comparison operator?": "A) ==    B) and    C) or    D) not",
    "Expression: not (False or True) and True evaluates to?": "A) True    B) False    C) Error    D) None",
    "What is the result of True == 1?": "A) True    B) False    C) Error    D) None",
    "Which of the following is treated as True in Python?": "A) Non-zero number    B) Empty string    C) 0    D) None",
    "Boolean expressions are used in which type of statements?": "A) if    B) print    C) def    D) import"
}

cs_ch7_mcq_answers = {
    "Which of the following is a valid Boolean expression?": "A",
    "What is the result of: not (True and False)?": "C",
    "Which operator is used for logical negation?": "C",
    "What does True and False evaluate to?": "A",
    "What type of operator is 'and'?": "A",
    "Which of these is a correct logical operator in Python?": "A",
    "What is the output of: 5 > 6?": "B",
    "Which set contains all Boolean operators?": "A",
    "Which operator is used to compare equality?": "A",
    "What is the output of: 2 + 3 * 1?": "C",
    "What is the output of not False?": "A",
    "Which of the following represents an invalid logical expression?": "C",
    "The result of True and not False is?": "A",
    "Which one is not a logical operator?": "D",
    "What is the data type of the expression (4 > 2)?": "C",
    "True or False and not True evaluates to?": "A",
    "What will be the result of 0 and 1?": "B",
    "In Python, which of these values is treated as False?": "A",
    "Which of the following returns True?": "A",
    "Which operator has the highest precedence?": "C",
    "not (True or False) evaluates to?": "A",
    "What is the output of (3 < 5) and (5 > 2)?": "A",
    "Which operator is used to represent inequality?": "A",
    "Boolean values are represented using which keywords in Python?": "B",
    "Logical operators return results of type?": "C",
    "Which of the following is a comparison operator?": "A",
    "Expression: not (False or True) and True evaluates to?": "B",
    "What is the result of True == 1?": "A",
    "Which of the following is treated as True in Python?": "A",
    "Boolean expressions are used in which type of statements?": "A"
}

true_false_cs_ch7 = {
    "The 'and' operator returns True only if both operands are True.": "True",
    "The 'or' operator returns False if any one operand is True.": "False",
    "'not True' evaluates to False.": "True",
    "Boolean expressions return numeric values only.": "False",
    "Comparison operators return Boolean values.": "True",
    "'0' (zero) is considered False in Boolean context.": "True",
    "'not False' is equivalent to True.": "True",
    "Logical operators include and, or, not.": "True",
    "The result of (3 > 2) and (5 < 10) is True.": "True",
    "Boolean values can be assigned to variables.": "True",
    "Python supports xor as a logical operator.": "False",
    "Every non-zero number is considered True in Boolean expressions.": "True",
    "The value None is considered True in Boolean tests.": "False",
    "The comparison operator '!=' means equal.": "False",
    "'True == 1' evaluates to True.": "True",
    "'False == 0' evaluates to True.": "True",
    "The not operator changes True to False and vice versa.": "True",
    "Boolean expressions are often used in 'if' statements.": "True",
    "'and' has higher precedence than 'not'.": "False",
    "The statement (not False) and True evaluates to True.": "True",
    "'True and False' is False.": "True",
    "Python uses '==' for assignment.": "False",
    "'or' returns True if either operand is True.": "True",
    "'not (True or False)' is False.": "True",
    "'not True or False' is False.": "True",
    "'not (False and True)' is True.": "True",
    "'and', 'or', and 'not' are case-sensitive in Python.": "True",
    "Boolean values are stored as 0 and 1 internally.": "True",
    "Python allows chaining of comparisons like 2 < x < 5.": "True",
    "Boolean logic is used only in loops.": "False"
}
