# cs/cs_ch17.py

cs_ch17_mcq_answers = {
    "Which data type is used to store a sequence of characters in Python?": "A",
    "Which symbol is used for string concatenation?": "B",
    "What does len('hello') return?": "D",
    "Which function converts all characters to uppercase?": "A",
    "What is the output of 'abc'.upper()?": "C",
    "Which function converts string to lowercase?": "D",
    "What is the index of the first character in a Python string?": "A",
    "What is the output of 'Hello'[1]?": "B",
    "What does 'apple'.find('p') return?": "A",
    "Which method removes spaces from both ends of a string?": "C",
    "Which of the following is a valid string slicing syntax?": "A",
    "What is the output of 'Python'[::-1]?": "D",
    "Which method returns True if string starts with a specified value?": "B",
    "Which function checks if all characters are digits?": "C",
    "What does 'hello'.replace('l', 'x') return?": "D",
    "Strings in Python are:": "B",
    "Which function splits a string into a list?": "A",
    "Which function joins list into a string?": "C",
    "What is the output of 'ab cd'.split()?": "B",
    "What does '123'.isdigit() return?": "A",
    "What is the result of 'Hi'*3?": "C",
    "What does '  hello  '.strip() return?": "D",
    "Which escape sequence inserts a new line?": "B",
    "Which symbol is used for multiline strings?": "D",
    "Which of these is not a string method?": "C",
    "What does ord('A') return?": "B"
}

cs_ch17_mcq_options = {
    "Which data type is used to store a sequence of characters in Python?": "A. str  B. int  C. char  D. float",
    "Which symbol is used for string concatenation?": "A. -  B. +  C. *  D. &",
    "What does len('hello') return?": "A. 6  B. 0  C. Error  D. 5",
    "Which function converts all characters to uppercase?": "A. upper()  B. capitalize()  C. title()  D. lower()",
    "What is the output of 'abc'.upper()?": "A. abc  B. Abc  C. ABC  D. abc()",
    "Which function converts string to lowercase?": "A. down()  B. lowercase()  C. capitalize()  D. lower()",
    "What is the index of the first character in a Python string?": "A. 0  B. 1  C. -1  D. None",
    "What is the output of 'Hello'[1]?": "A. H  B. e  C. l  D. o",
    "What does 'apple'.find('p') return?": "A. 1  B. 0  C. 2  D. -1",
    "Which method removes spaces from both ends of a string?": "A. trim()  B. remove()  C. strip()  D. slice()",
    "Which of the following is a valid string slicing syntax?": "A. s[1:4]  B. s[1:4:0]  C. s(1:4)  D. s{1:4}",
    "What is the output of 'Python'[::-1]?": "A. Error  B. Python  C. nohtyP  D. nohtyP",
    "Which method returns True if string starts with a specified value?": "A. isstart()  B. startswith()  C. starts()  D. beginswith()",
    "Which function checks if all characters are digits?": "A. num()  B. digit()  C. isdigit()  D. isnum()",
    "What does 'hello'.replace('l', 'x') return?": "A. hexxo  B. hexxl  C. heloo  D. hexxo",
    "Strings in Python are:": "A. Mutable  B. Immutable  C. Static  D. Dynamic",
    "Which function splits a string into a list?": "A. split()  B. break()  C. divide()  D. list()",
    "Which function joins list into a string?": "A. append()  B. add()  C. join()  D. merge()",
    "What is the output of 'ab cd'.split()?": "A. ['ab cd']  B. ['ab', 'cd']  C. abcd  D. ['a','b','c','d']",
    "What does '123'.isdigit() return?": "A. True  B. False  C. 123  D. Error",
    "What is the result of 'Hi'*3?": "A. Hi3  B. Error  C. HiHiHi  D. Hi*3",
    "What does '  hello  '.strip() return?": "A. hello  B.  hello  C. hello  D. hello",
    "Which escape sequence inserts a new line?": "A. /n  B. \\n  C. %n  D. nl",
    "Which symbol is used for multiline strings?": "A. '''  B. '  C. \"  D. \"\"\"",
    "Which of these is not a string method?": "A. split()  B. join()  C. append()  D. replace()",
    "What does ord('A') return?": "A. 97  B. 65  C. A  D. Error"
}

true_false_cs_ch17 = {
    "Strings in Python are immutable.": "T",
    "String indexing in Python starts at 0.": "T",
    "The + operator is used to join strings.": "T",
    "The len() function returns the length of a string.": "T",
    "The strip() function removes characters from the middle.": "F",
    "upper() converts all characters in a string to lowercase.": "F",
    "Strings can be multiplied using * operator.": "T",
    "find() returns -1 if the substring is not found.": "T",
    "A string is a sequence of Unicode characters.": "T",
    "Slicing works on strings.": "T",
    "Python strings are mutable.": "F",
    "The method isdigit() returns True only if all characters are digits.": "T",
    "The in operator checks if a substring exists.": "T",
    "Python uses ' as well as \" for strings.": "T",
    "String methods change the original string.": "F",
    "You can use a for loop to iterate through a string.": "T",
    "Python does not allow multi-line strings.": "F",
    "join() is used to combine string elements from a list.": "T",
    "capitalize() capitalizes the first letter.": "T",
    "lower() converts string to lowercase.": "T",
    "ord() returns ASCII value of a character.": "T",
    "Strings cannot contain spaces.": "F",
    "split() returns a list of strings.": "T",
    "replace() replaces one substring with another.": "T",
    "isalnum() returns True if all characters are alphanumeric.": "T",
    "String methods can be chained.": "T"
}
