true_false_eng_ch1 = {
    "The author’s grandmother was young and beautiful.": "F",
    "The author’s grandmother always wore white clothes.": "T",
    "The grandmother had a peaceful and calm face.": "T",
    "The author and his grandmother were very close.": "T",
    "The grandmother helped the author with his homework.": "F",
    "The grandmother believed in modern education.": "F",
    "The author studied in an English medium school.": "T",
    "The grandmother could read English fluently.": "F",
    "The grandmother used to feed dogs in the village.": "T",
    "The author’s parents lived in the village with him.": "F",
    "The author moved to the city with his grandmother.": "T",
    "In the city, the grandmother continued feeding street dogs.": "F",
    "The grandmother spent most of her time spinning and praying.": "T",
    "The grandmother disliked music and found it indecent.": "T",
    "The grandmother accompanied the author to school in the city.": "F",
    "The grandmother was upset when the author went abroad.": "F",
    "The grandmother prayed constantly after the author left for abroad.": "T",
    "The author was away for five years.": "T",
    "The grandmother welcomed the author with loud laughter on his return.": "F",
    "The grandmother fell ill the same evening the author returned.": "T",
    "The grandmother died while praying.": "T",
    "After her death, birds flew away chirping loudly.": "F",
    "The family offered food to the birds after her death.": "T",
    "The birds ate all the food offered to them.": "F",
    "The grandmother’s room was always filled with the smell of tulsi.": "F",
    "The author described his grandmother as eternally old.": "T",
    "The grandmother had a stoop and hobbled around the house.": "T",
    "The author shared a room with his grandmother in the city.": "T",
    "The grandmother used to sing devotional songs in the morning.": "F",
    "The grandmother had deep religious faith.": "T",
    "The grandmother considered music suitable for the rich.": "F",
    "The author’s parents sent him to a modern school.": "T",
    "The author studied science and English in school.": "T",
    "The grandmother asked the author about his school lessons.": "F",
    "The grandmother believed in the scriptures and God.": "T",
    "The author and grandmother had a silent relationship.": "F",
    "The grandmother used to read the Bible daily.": "F",
    "The grandmother became more withdrawn after the author went abroad.": "T",
    "The grandmother spent the last few hours of her life in prayer.": "T",
    "The grandmother’s body was cremated the same day.": "T",
    "The birds mourned silently around her dead body.": "T",
    "The author wept uncontrollably at his grandmother’s death.": "F",
    "The author’s family lived in a joint family system.": "F",
    "The grandmother had silver hair and wrinkled skin.": "T",
    "The author described her as not very religious.": "F",
    "The grandmother was fond of stories from the scriptures.": "T",
    "The author never saw his grandmother looking young.": "T",
    "The grandmother had a kind and caring nature.": "T",
    "The grandmother disliked the city life.": "F",
    "The grandmother danced with the birds before she died.": "F"
}

eng_ch1_mcq_answers = {
    "What did the author’s grandmother always wear?": "A",
    "How did the author describe his grandmother’s appearance?": "C",
    "What did the grandmother do in the village?": "B",
    "Who taught the author in the village?": "A",
    "Which subject made the grandmother unhappy in the city?": "D",
    "What did the grandmother carry to the temple?": "B",
    "Why did the grandmother dislike music?": "D",
    "Where did the author and grandmother shift after village life?": "C",
    "How did the grandmother spend her time in the city?": "C",
    "What did the grandmother feed in the village?": "A",
    "What animals did the grandmother feed in the city?": "D",
    "What was the grandmother’s reaction to the author going abroad?": "B",
    "What happened the evening after the author returned from abroad?": "A",
    "What did the grandmother do during her last moments?": "C",
    "How did the birds react to the grandmother’s death?": "B",
    "What surprised the family after the grandmother's death?": "C",
    "How many years was the author away abroad?": "D",
    "Which book did the grandmother constantly read?": "B",
    "What type of relationship did the author and grandmother share?": "A",
    "What did the author never see his grandmother doing?": "D",
    "What did the grandmother do every evening in the city?": "C",
    "How did the author’s parents live compared to him in childhood?": "A",
    "What feature made the grandmother look like she never aged?": "B",
    "Why did the grandmother stop talking to the author in the city?": "C",
    "Who is the author of ‘The Portrait of a Lady’?": "D",
    "Which religion did the grandmother strictly follow?": "A",
    "What subject did the author study in the city school?": "B",
    "Why did the grandmother become quiet after moving to the city?": "D",
    "What was the grandmother doing in her last hours?": "A",
    "How long did the birds stay around the dead body?": "B",
    "What did the author and grandmother share in the village?": "C",
    "Which physical activity was never mentioned in the grandmother's routine?": "B",
    "What did the grandmother dislike about the city school?": "D",
    "Which act shows the grandmother’s religious nature?": "A",
    "What did the grandmother do with her spinning wheel?": "C",
    "What food was offered to the birds after her death?": "D",
    "What was the grandmother’s face compared to?": "B",
    "How did the family react to the birds' silence?": "A",
    "What was the grandmother’s reaction to music lessons?": "C",
    "Which word best describes the grandmother’s personality?": "D",
    "What did the grandmother stop doing after the author's schooling began?": "A",
    "What did the grandmother do when the author returned from abroad?": "B",
    "Why did the grandmother feed street dogs in the village?": "C",
    "What is the central theme of the story?": "D",
    "How did the grandmother die?": "A",
    "What does the story highlight about relationships?": "D",
    "How was the grandmother’s connection to rituals shown?": "B",
    "What makes the birds' behavior symbolic?": "C",
    "What emotion does the story end with?": "A",
    "What aspect of life does the story portray well?": "D"
}

eng_ch1_mcq_options = {
    "What did the author’s grandmother always wear?": "A. White saree  B. Red gown  C. Blue shawl  D. Green dupatta",
    "How did the author describe his grandmother’s appearance?": "A. Beautiful and young  B. Weak and sad  C. Wrinkled and old  D. Bright and energetic",
    "What did the grandmother do in the village?": "A. Cooked for the family  B. Took the author to school  C. Managed the farm  D. Fed the cows",
    "Who taught the author in the village?": "A. The priest  B. His grandmother  C. His uncle  D. The tutor",
    "Which subject made the grandmother unhappy in the city?": "A. Hindi  B. History  C. Moral science  D. Science",
    "What did the grandmother carry to the temple?": "A. Flowers  B. A bundle of stale chapatis  C. A holy book  D. Water",
    "Why did the grandmother dislike music?": "A. It was too loud  B. It had no words  C. It distracted from studies  D. It was indecent for gentlefolk",
    "Where did the author and grandmother shift after village life?": "A. Hostel  B. New village  C. City  D. Another house",
    "How did the grandmother spend her time in the city?": "A. Talking with neighbors  B. Watching TV  C. Spinning and praying  D. Cooking",
    "What did the grandmother feed in the village?": "A. Street dogs  B. Cats  C. Birds  D. Chickens",
    "What animals did the grandmother feed in the city?": "A. Dogs  B. Cows  C. Horses  D. Sparrows",
    "What was the grandmother’s reaction to the author going abroad?": "A. She cried  B. She accepted it calmly  C. She argued  D. She fell sick",
    "What happened the evening after the author returned from abroad?": "A. She fell ill  B. She danced  C. She cooked  D. She gave a lecture",
    "What did the grandmother do during her last moments?": "A. Prayed and told beads  B. Wrote a letter  C. Slept peacefully  D. Talked to family",
    "How did the birds react to the grandmother’s death?": "A. Flew away  B. Sat quietly  C. Chirped loudly  D. Ate food",
    "What surprised the family after the grandmother's death?": "A. The light went off  B. The priest didn’t come  C. Birds gathered silently  D. Her body disappeared",
    "How many years was the author away abroad?": "A. 2  B. 3  C. 4  D. 5",
    "Which book did the grandmother constantly read?": "A. Bible  B. Scriptures  C. History  D. Ramayana",
    "What type of relationship did the author and grandmother share?": "A. Deep and loving  B. Angry and cold  C. Competitive  D. Formal",
    "What did the author never see his grandmother doing?": "A. Cooking  B. Praying  C. Feeding animals  D. Looking young",
    "What did the grandmother do every evening in the city?": "A. Cooked dinner  B. Sang bhajans  C. Fed sparrows  D. Cleaned the room",
    "How did the author’s parents live compared to him in childhood?": "A. In the city  B. With him  C. In the village  D. Abroad",
    "What feature made the grandmother look like she never aged?": "A. Hair  B. Wrinkles  C. Smile  D. Voice",
    "Why did the grandmother stop talking to the author in the city?": "A. She became deaf  B. She was angry  C. His studies changed  D. He didn’t pray",
    "Who is the author of ‘The Portrait of a Lady’?": "A. R. K. Narayan  B. Ruskin Bond  C. Rabindranath Tagore  D. Khushwant Singh",
    "Which religion did the grandmother strictly follow?": "A. Sikhism  B. Islam  C. Christianity  D. Jainism",
    "What subject did the author study in the city school?": "A. Sanskrit  B. English  C. Music  D. Drawing",
    "Why did the grandmother become quiet after moving to the city?": "A. She was sick  B. She was ignored  C. She had no friends  D. She felt disconnected",
    "What was the grandmother doing in her last hours?": "A. Praying  B. Sleeping  C. Crying  D. Eating",
    "How long did the birds stay around the dead body?": "A. Few minutes  B. Several hours  C. Whole day  D. One night",
    "What did the author and grandmother share in the village?": "A. A house  B. A kitchen  C. A room  D. A temple",
    "Which physical activity was never mentioned in the grandmother's routine?": "A. Feeding animals  B. Jogging  C. Praying  D. Spinning",
    "What did the grandmother dislike about the city school?": "A. Language  B. Uniform  C. Teachers  D. No teaching of God",
    "Which act shows the grandmother’s religious nature?": "A. Saying prayers  B. Teaching Quran  C. Going to church  D. None",
    "What did the grandmother do with her spinning wheel?": "A. Played music  B. Cooked food  C. Spun thread  D. Cleaned dishes",
    "What food was offered to the birds after her death?": "A. Bread  B. Fruits  C. Rice  D. Crumbs",
    "What was the grandmother’s face compared to?": "A. A flower  B. Peaceful landscape  C. Goddess  D. Stone",
    "How did the family react to the birds' silence?": "A. Shocked  B. Ignored  C. Angry  D. Happy",
    "What was the grandmother’s reaction to music lessons?": "A. Excited  B. Indifferent  C. Disapproving  D. Joyful",
    "Which word best describes the grandmother’s personality?": "A. Arrogant  B. Lazy  C. Modern  D. Devout",
    "What did the grandmother stop doing after the author's schooling began?": "A. Helping in studies  B. Spinning  C. Praying  D. Feeding birds",
    "What did the grandmother do when the author returned from abroad?": "A. Hugged him  B. Sang in celebration  C. Cried  D. Cooked his meal",
    "Why did the grandmother feed street dogs in the village?": "A. Hobby  B. Habit  C. Compassion  D. Ritual",
    "What is the central theme of the story?": "A. Nature  B. Politics  C. Humor  D. Human relationships",
    "How did the grandmother die?": "A. Peacefully  B. With pain  C. In sleep  D. In hospital",
    "What does the story highlight about relationships?": "A. Hatred  B. Jealousy  C. Conflict  D. Love and bonding",
    "How was the grandmother’s connection to rituals shown?": "A. Festivals  B. Daily prayers  C. Donations  D. Pilgrimage",
    "What makes the birds' behavior symbolic?": "A. Circle of life  B. Anger  C. Respect for her soul  D. Celebration",
    "What emotion does the story end with?": "A. Peace  B. Regret  C. Fear  D. Shock",
    "What aspect of life does the story portray well?": "A. Technology  B. Travel  C. Fantasy  D. Simplicity and faith"
}